ARROWS = {
  'Mundane': {
    'weight': 5,
    'types': ['Impact', 'Bola', 'Smoke Powder', 'Poison Bas']
  },
  'Common': {
    'weight': 4,
    'types': ['Sonic', 'Unbreakable', 'Walloping']
  },
  'Uncommon': {
    'weight': 3,
    'types': [
      '+1 Arrow',
      'Dried Leech'
      'Acid Flux Tipped',
      'Cold Flux Tipped',
      'Fire Flux Tipped',
      'Lightning Flux Tipped',
      'Poison Flux Tipped',
      'Thunder Flux Tipped',
      'Winged'
    ]
  },
  'Rare': {
    'weight': 2,
    'types': [
      '+2 Arrow',
      'Burst',
      'Concussive',
      'Net',
      'Force Flux Tipped',
      'Necrotic Flux Tipped',
      'Psychic Flux Tipped',
      'Radiant Flux Tipped',
      'Acid Flux Incorporated',
      'Cold Flux Incorporated',
      'Fire Flux Incorporated',
      'Lightning Flux Incorporated',
      'Poison Flux Incorporated',
      'Thunder Flux Incorporated'
    ]
  },
  'Very Rare': {
    'weight': 1,
    'types': [
      '+3 Arrow',
      'Ethereal',
      'Splitting',
      'Force Flux Incorporated',
      'Necrotic Flux Incorporated',
      'Psychic Flux Incorporated',
      'Radiant Flux Incorporated',
      'Bloodseeker'
    ]
  }
}

SLAYING = [
  'Aberration',
  'Celestial',
  'Dragon',
  'Elemental',
  'Fey',
  'Fiend',
  'Giant',
  'Monster',
  'Ooze',
  'Undead',
]

class Item:
  def __init__(self, name: str, price: int, itype: str, attunement: bool, rarity: str, options: list[str] = []):
    self.name = name
    self.price = price
    self.type = itype
    self.attunement = attunement
    self.rarity = rarity
    self.options = options

  def __str__(self):
    string = f"{self.name}"
    if self.attunement: string += " (requires attunement)"
    string += f", {self.rarity} {self.type}: {self.price}gp"
    return string
  
  def __repr__(self):
    return f"{self.name}"

class Armor:
  def __init__(self, name: str, price: int, atype: str):
    self.name = name
    self.price = price
    self.type = atype
  
  def __str__(self):
    return f"{self.name} Armor"
  def __repr__(self):
    return f"{self.name}"

class Weapon:
  def __init__(self, name: str, price: int, prof: str, wtype: str, wclass: str, dtype: str, props: list[str]):
    self.name = name
    self.price = price
    self.prof = prof # simple or martial
    self.type = wtype # melee or ranged
    self.wclass = wclass # dagger, polearm, sword, axe, blunt
    self.dtype = dtype # damage type
    self.props = props # list of strings
  
  def __str__(self):
    return f"{self.name} ({self.prof} {self.type} Weapon)"
  def __repr__(self):
    return f"{self.name}"

class Spell:
  def __init__(self, name: str, level: int, school: str):
    self.name = name
    self.level = level
    self.school = school
  
  def __str__(self):
    string = ""
    if self.level > 0:
      special_suffixes = ["st", "nd", "rd"]
      suffix = "th" if self.level > 3 else special_suffixes[self.level - 1]
      string = f"{self.name} ({self.level}{suffix} level {self.school})"
    else:
      string = f"{self.name} ({self.school} Cantrip)"
    return string
  def __repr__(self):
    return self.name


ARMOR = [
  Armor("Padded", 5, "Light"),
  Armor("Leather", 10, "Light"),
  Armor("Studded Leather", 45, "Light"),
  Armor("Hide", 10, "Medium"),
  Armor("Chain Shirt", 50, "Medium"),
  Armor("Scale Mail", 50, "Medium"),
  Armor("Breastplate", 400, "Medium"),
  Armor("Half Plate", 750, "Medium"),
  Armor("Ring Mail", 30, "Heavy"),
  Armor("Chain Mail", 75, "Heavy"),
  Armor("Splint", 200, "Heavy"),
  Armor("Plate", 1500, "Heavy"),
]
LIGHT_ARMOR = [item for item in ARMOR if item.type == "Light"]
MEDIUM_ARMOR = [item for item in ARMOR if item.type == "Medium"]
HEAVY_ARMOR = [item for item in ARMOR if item.type == "Heavy"]
SHIELDS = [
  # Armor("Buckler Shield", 50, "Shield"),
  Armor("Shield", 10, "Shield"),
]
PLATE = [a for a in ARMOR if a.name == "Plate"]

B = "Bludgeoning"
P = "Piercing"
S = "Slashing"

WEAPONS = [
  Weapon("Club", 1, "Simple", "Melee", "Blunt", B, ["Light"]),
  Weapon("Dagger", 2, "Simple", "Melee", "Dagger", P, ["Light", "Finesse", "Thrown"]),
  Weapon("Greatclub", 1, "Simple", "Melee", "Blunt", B, ["Two-Handed"]),
  Weapon("Handaxe", 5, "Simple", "Melee", "Axe", S, ["Light", "Thrown"]),
  Weapon("Javelin", 1, "Simple", "Melee", "Spear", P, ["Thrown"]),
  Weapon("Light Hammer", 2, "Simple", "Melee", "Blunt", B, ["Light", "Thrown"]),
  Weapon("Mace", 5, "Simple", "Melee", "Blunt", B, []),
  Weapon("Quarterstaff", 1, "Simple", "Melee", "Blunt", B, ["Versatile"]),
  Weapon("Sickle", 1, "Simple", "Melee", "Sickle", S, ["Light"]),
  Weapon("Spear", 1, "Simple", "Melee", "Spear", P, ["Thrown", "Versatile"]),
  Weapon("Boomerang", 15, "Simple", "Ranged", B, "Boomerang", []),
  Weapon("Light Crossbow", 25, "Simple", "Ranged", P, "Crossbow", ["Two-Handed"]),
  Weapon("Dart", 1, "Simple", "Ranged", "Dart", P, ["Finesse", "Thrown"]),
  Weapon("Shortbow", 25, "Simple", "Ranged", "Bow", P, ["Two-Handed"]),
  Weapon("Sling", 1, "Simple", "Ranged", "Sling", B, []),
  Weapon("Battleaxe", 10, "Martial", "Melee", "Axe", S, ["Versatile"]),
  Weapon("Flail", 10, "Martial", "Melee", "Blunt", P, []),
  Weapon("Glaive", 20, "Martial", "Melee", "Polearm", S, ["Heavy", "Reach", "Two-Handed"]),
  Weapon("Greataxe", 30, "Martial", "Melee", "Axe", S, ["Heavy", "Two-Handed"]),
  Weapon("Greatsword", 50, "Martial", "Melee", "Sword", S, ["Heavy", "Two-Handed"]),
  Weapon("Halberd", 20, "Martial", "Melee", "Polearm", S, ["Heavy", "Reach", "Two-Handed"]),
  Weapon("Lance", 10, "Martial", "Melee", "Lance", P, ["Reach", "Special"]),
  Weapon("Longsword", 15, "Martial", "Melee", "Sword", S, ["Versatile"]),
  Weapon("Maul", 10, "Martial", "Melee", "Blunt", B, ["Heavy", "Two-Handed"]),
  Weapon("Morningstar", 15, "Martial", "Melee", P, "Blunt", []),
  Weapon("Pike", 5, "Martial", "Melee", "Polearm", P, ["Heavy", "Reach", "Two-Handed"]),
  Weapon("Rapier", 25, "Martial", "Melee", "Sword", P, ["Finesse"]),
  Weapon("Scimitar", 25, "Martial", "Melee", "Sword", S, ["Finesse", "Light"]),
  Weapon("Shortsword", 10, "Martial", "Melee", "Sword", P, ["Finesse", "Light"]),
  Weapon("Trident", 5, "Martial", "Melee", "Spear", P, ["Heavy", "Reach", "Two-Handed"]),
  Weapon("War Pick", 5, "Martial", "Melee", "Pick", P, []),
  Weapon("Warhammer", 15, "Martial", "Melee", "Blunt", B, ["Versatile"]),
  Weapon("Whip", 2, "Martial", "Melee", "Whip", S, ["Finesse", "Reach"]),
  Weapon("Blowgun", 10, "Martial", "Ranged", "Blowgun", P, []),
  Weapon("Hand Crossbow", 75, "Martial", "Ranged", "Crossbow", P, ["Light"]),
  Weapon("Heavy Crossbow", 50, "Martial", "Ranged", "Crossbow", P, ["Two-Handed", "Heavy"]),
  Weapon("Longbow", 50, "Martial", "Ranged", "Bow", P, ["Heavy", "Two-Handed"]),
  Weapon("Musket", 500, "Martial", "Ranged", "Firearm", P, ["Two-Handed"]),
  Weapon("Pistol", 250, "Martial", "Ranged", "Firearm", P, []),
]
SIMPLE_WEAPONS = [weapon for weapon in WEAPONS if weapon.prof == "Simple"]
MARTIAL_WEAPONS = [weapon for weapon in WEAPONS if weapon.prof == "Martial"]
MELEE_WEAPONS = [weapon for weapon in WEAPONS if weapon.type == "Melee"]
RANGED_WEAPONS = [weapon for weapon in WEAPONS if weapon.type == "Ranged"]
AXES = [weapon for weapon in WEAPONS if weapon.wclass == "Axe"]
BLUNT = [weapon for weapon in WEAPONS if weapon.wclass == "Blunt"]
BOWS = [weapon for weapon in WEAPONS if weapon.wclass == "Bow"]
CROSSBOWS = [weapon for weapon in WEAPONS if weapon.wclass == "Crossbow"]
POLEARMS = [weapon for weapon in WEAPONS if weapon.wclass == "Polearm"] + [weapon for weapon in WEAPONS if weapon.name == "Spear" or weapon.name == "Quarterstaff"]
SPEARS = [weapon for weapon in WEAPONS if weapon.wclass == "Spear"]
SWORDS = [weapon for weapon in WEAPONS if weapon.wclass == "Sword"]
MACE = [weapon for weapon in WEAPONS if weapon.name == "Mace"]
DAGGER = [weapon for weapon in WEAPONS if weapon.wclass == "Dagger"]
FIREARMS = [weapon for weapon in WEAPONS if weapon.wclass == "Firearm"]

ABJ = "Abjuration"
CON = "Conjuration"
DIV = "Divination"
ENC = "Enchantment"
EVO = "Evocation"
ILL = "Illusion"
NEC = "Necromancy"
TRA = "Transmutation"

SPELLS = [
  Spell("Abi-Dalzim's Horrid Wilting", 8, NEC),
  Spell("Absorb Elements", 1, ABJ),
  Spell("Acid Splash", 0, EVO),
  Spell("Aganazzar's Scorcher", 2, EVO),
  Spell("Aid", 2, ABJ),
  Spell("Alarm", 1, ABJ),
  Spell("Alter Self", 2, TRA),
  Spell("Animal Friendship", 1, ENC),
  Spell("Animal Messenger", 2, ENC),
  Spell("Animal Shapes", 8, TRA),
  Spell("Animate Dead", 3, NEC),
  Spell("Animate Objects", 5, TRA),
  Spell("Antagonize", 3, ENC),
  Spell("Antilife Shell", 5, ABJ),
  Spell("Antimagic", 8, ABJ),
  Spell("Antipathy/Sympathy", 8, ENC),
  Spell("Arcane Eye", 4, DIV),
  Spell("Arcane Gate", 6, CON),
  Spell("Arcane Lock", 2, ABJ),
  Spell("Arcane Vigor", 2, ABJ),
  Spell("Armor of Agathys", 1, ABJ),
  Spell("Arms of Hadar", 1, CON),
  Spell("Ashardalon's Stride", 3, TRA),
  Spell("Astral Projection", 9, NEC),
  Spell("Augury", 2, DIV),
  Spell("Aura of Life", 4, ABJ),
  Spell("Aura of Purity", 4, ABJ),
  Spell("Aura of Vitality", 3, EVO),
  Spell("Awaken", 5, TRA),
  Spell("Bane", 1, ENC),
  Spell("Banishing Smite", 5, CON),
  Spell("Banishment", 4, ABJ),
  Spell("Barkskin", 2, TRA),
  Spell("Beacon of Hope", 3, ABJ),
  Spell("Beast Bond", 1, DIV),
  Spell("Beast Sense", 2, DIV),
  Spell("Befuddlement", 8, ENC),
  Spell("Bestow Curse", 3, NEC),
  Spell("Bigby's Hand", 5, EVO),
  Spell("Blade Barrier", 6, EVO),
  Spell("Blade of Disaster", 9, CON),
  Spell("Blade Ward", 0, ABJ),
  Spell("Bless", 1, ENC),
  Spell("Blight", 4, NEC),
  Spell("Blinding Smite", 3, EVO),
  Spell("Blindness/Deafness", 2, NEC),
  Spell("Blink", 3, TRA),
  Spell("Blur", 2, ILL),
  Spell("Bolt Strike", 5, EVO),
  Spell("Bones of the Earth", 6, TRA),
  Spell("Booming Blade", 0, EVO),
  Spell("Borrowed Knowledge", 2, DIV),
  Spell("Burning Hands", 1, EVO),
  Spell("Call Lightning", 3, CON),
  Spell("Calm Emotions", 2, ENC),
  Spell("Catapult", 1, TRA),
  Spell("Catnap", 3, ENC),
  Spell("Cause Fear", 1, NEC),
  Spell("Ceremony", 1, ABJ),
  Spell("Chain Lightning", 6, EVO),
  Spell("Chaos Bolt", 1, EVO),
  Spell("Charm Monster", 4, ENC),
  Spell("Charm Person", 1, ENC),
  Spell("Chill Touch", 0, NEC),
  Spell("Chromatic Orb", 1, EVO),
  Spell("Circle of Death", 6, NEC),
  Spell("Circle of Power", 5, ABJ),
  Spell("Clairvoyance", 3, DIV),
  Spell("Clone", 8, NEC),
  Spell("Cloud of Daggers", 2, CON),
  Spell("Cloudkill", 5, CON),
  Spell("Color Spray", 1, ILL),
  Spell("Command", 1, ENC),
  Spell("Commune", 5, DIV),
  Spell("Commune with Nature", 5, DIV),
  Spell("Compelled Duel", 1, ENC),
  Spell("Comprehend Languages", 1, DIV),
  Spell("Compulsion", 4, ENC),
  Spell("Cone of Cold", 5, EVO),
  Spell("Confusion", 4, ENC),
  Spell("Conjure Animals", 3, CON),
  Spell("Conjure Barrage", 3, CON),
  Spell("Conjure Celestial", 7, CON),
  Spell("Conjure Elemental", 5, CON),
  Spell("Conjure Fey", 6, CON),
  Spell("Conjure Minor Elemental", 4, CON),
  Spell("Conjure Volley", 5, CON),
  Spell("Conjure Woodland Beings", 4, CON),
  Spell("Contact Other Plane", 5, DIV),
  Spell("Contagion", 5, NEC),
  Spell("Contingency", 6, EVO),
  Spell("Continual Flame", 2, EVO),
  Spell("Control Flames", 0, TRA),
  Spell("Control Water", 4, TRA),
  Spell("Control Weather", 8, TRA),
  Spell("Control Winds", 5, TRA),
  Spell("Cordon of Arrows", 2, TRA),
  Spell("Counterspell", 3, ABJ),
  Spell("Create Bonfire", 0, CON),
  Spell("Create Food and Water", 3, CON),
  Spell("Create Homunculus", 6, TRA),
  Spell("Create or Destroy Water", 1, TRA),
  Spell("Create Undead", 6, NEC),
  Spell("Creation", 5, ILL),
  Spell("Crown of Madness", 2, ENC),
  Spell("Crown of Stars", 7, EVO),
  Spell("Crusader's Mantle", 3, EVO),
  Spell("Cure Wounds", 1, ABJ),
  Spell("Dancing Lights", 0, ILL),
  Spell("Danse Macabre", 5, NEC),
  Spell("Dark Star", 8, EVO),
  Spell("Darkness", 2, EVO),
  Spell("Darkvision", 2, TRA),
  Spell("Dawn", 5, EVO),
  Spell("Daylight", 3, EVO),
  Spell("Death Ward", 4, ABJ),
  Spell("Delayed Blast Fireball", 7, EVO),
  Spell("Demiplane", 8, CON),
  Spell("Destructive Wave", 5, EVO),
  Spell("Detect Evil and Good", 1, DIV),
  Spell("Detect Magic", 1, DIV),
  Spell("Detect Poison and Disease", 1, DIV),
  Spell("Detect Thoughts", 2, DIV),
  Spell("Dimension Door", 4, CON),
  Spell("Disguise Self", 1, ILL),
  Spell("Disintegrate", 6, TRA),
  Spell("Dispel Evil and Good", 5, ABJ),
  Spell("Dispel Magic", 3, ABJ),
  Spell("Dissonant Whispers", 1, ENC),
  Spell("Divination", 4, DIV),
  Spell("Divine Favor", 1, EVO),
  Spell("Divine Lightning", 3, EVO),
  Spell("Divine Smite", 1, TRA),
  Spell("Divine Word", 7, EVO),
  Spell("Dominate Beast", 4, ENC),
  Spell("Dominate Monster", 8, ENC),
  Spell("Dominate Person", 5, ENC),
  Spell("Draconic Transformation", 7, TRA),
  Spell("Dragon's Breath", 2, TRA),
  Spell("Drawmij's Instant Summons", 6, CON),
  Spell("Dream", 5, ILL),
  Spell("Druid Grove", 6, ABJ),
  Spell("Druidcraft", 0, TRA),
  Spell("Dust Devil", 2, CON),
  Spell("Earth Tremor", 1, EVO),
  Spell("Earthbind", 2, TRA),
  Spell("Earthquake", 8, TRA),
  Spell("Eldritch Blast", 0, EVO),
  Spell("Elemental Bane", 4, TRA),
  Spell("Elemental Weapon", 3, TRA),
  Spell("Elementalism", 0, TRA),
  Spell("Enemies Abound", 3, ENC),
  Spell("Enervation", 5, NEC),
  Spell("Enhance Ability", 2, TRA),
  Spell("Enlarge/Reduce", 2, TRA),
  Spell("Ensnaring Strike", 1, CON),
  Spell("Entangle", 1, CON),
  Spell("Enthrall", 2, ENC),
  Spell("Erupting Earth", 3, TRA),
  Spell("Etherealness", 7, TRA),
  Spell("Evard's Black Tentacles", 4, CON),
  Spell("Expeditious Retreat", 1, TRA),
  Spell("Eyebite", 6, NEC),
  Spell("Fabricate", 4, TRA),
  Spell("Faerie Fire", 1, EVO),
  Spell("False Life", 1, NEC),
  Spell("Far Step", 5, CON),
  Spell("Fear", 3, ILL),
  Spell("Feather Fall", 1, TRA),
  Spell("Feign Death", 3, NEC),
  Spell("Find Familiar", 1, CON),
  Spell("Find Greater Steed", 4, CON),
  Spell("Find Steed", 2, CON),
  Spell("Find the Path", 6, DIV),
  Spell("Find Traps", 2, DIV),
  Spell("Finger of Death", 7, NEC),
  Spell("Fire Bolt", 0, EVO),
  Spell("Fire Shield", 4, EVO),
  Spell("Fire Storm", 7, EVO),
  Spell("Fireball", 3, EVO),
  Spell("Fizban's Platinum Shield", 6, ABJ),
  Spell("Flame Arrows", 3, TRA),
  Spell("Flame Blade", 2, EVO),
  Spell("Flame Strike", 5, EVO),
  Spell("Flaming Sphere", 2, CON),
  Spell("Flesh to Stone", 6, TRA),
  Spell("Fly", 3, TRA),
  Spell("Fog Cloud", 1, CON),
  Spell("Forbiddance", 6, ABJ),
  Spell("Forcecage", 7, EVO),
  Spell("Foresight", 9, DIV),
  Spell("Fortune's Favor", 2, DIV),
  Spell("Fount of Moonlight", 4, EVO),
  Spell("Freedom of Movement", 4, ABJ),
  Spell("Freedom of the Waves", 3, CON),
  Spell("Freedom of the Winds", 5, ABJ),
  Spell("Friends", 0, ENC),
  Spell("Frostbite", 0, EVO),
  Spell("Gaseous Form", 3, TRA),
  Spell("Gate", 9, CON),
  Spell("Geas", 5, ENC),
  Spell("Gentle Repose", 2, NEC),
  Spell("Giant Insect", 4, CON),
  Spell("Gift of Alacrity", 1, DIV),
  Spell("Glibness", 8, TRA),
  Spell("Globe of Invulnerability", 6, ABJ),
  Spell("Glyph of Warding", 3, ABJ),
  Spell("Goodberry", 1, TRA),
  Spell("Grasping Vine", 4, CON),
  Spell("Gravity Fissure", 6, EVO),
  Spell("Gravity Sinkhole", 4, EVO),
  Spell("Grease", 1, CON),
  Spell("Greater Invisibility", 4, ILL),
  Spell("Greater Restoration", 5, ABJ),
  Spell("Green-Flame Blade", 0, EVO),
  Spell("Guardian of Faith", 4, CON),
  Spell("Guardian of Nature", 4, TRA),
  Spell("Guards and Wards", 6, ABJ),
  Spell("Guidance", 0, DIV),
  Spell("Guiding Bolt", 1, EVO),
  Spell("Gust", 0, TRA),
  Spell("Gust of Wind", 2, EVO),
  Spell("Hail of Thorns", 1, CON),
  Spell("Hallow", 5, ABJ),
  Spell("Hallucinatory Terrain", 4, ILL),
  Spell("Harm", 6, NEC),
  Spell("Haste", 3, TRA),
  Spell("Heal", 6, ABJ),
  Spell("Healing Spirit", 2, CON),
  Spell("Healing Word", 1, ABJ),
  Spell("Heat Metal", 2, TRA),
  Spell("Hellish Rebuke", 1, EVO),
  Spell("Heroes's Feast", 6, CON),
  Spell("Heroism", 1, ENC),
  Spell("Hex", 1, ENC),
  Spell("Hold Monster", 5, ENC),
  Spell("Hold Person", 2, ENC),
  Spell("Holy Aura", 8, ABJ),
  Spell("Holy Weapon", 5, EVO),
  Spell("Hunger of Hadar", 3, CON),
  Spell("Hunter's Mark", 1, DIV),
  Spell("Hypnotic Pattern", 3, ILL),
  Spell("Ice Knife", 1, CON),
  Spell("Ice Storm", 4, EVO),
  Spell("Identify", 1, DIV),
  Spell("Illusory Dragon", 8, ILL),
  Spell("Illusory Script", 1, ILL),
  Spell("Immolation", 5, EVO),
  Spell("Immovable Object", 2, TRA),
  Spell("Imprisonment", 9, ABJ),
  Spell("Incendiary Cloud", 8, CON),
  Spell("Infernal Calling", 5, CON),
  Spell("Infestation", 0, CON),
  Spell("Inflict Wounds", 1, NEC),
  Spell("Insect Plague", 5, CON),
  Spell("Intellect Fortress", 3, ABJ),
  Spell("Investiture of Flame", 6, TRA),
  Spell("Investiture of Ice", 6, TRA),
  Spell("Investiture of Stone", 6, TRA),
  Spell("Investiture of Wind", 6, TRA),
  Spell("Invisibility", 2, ILL),
  Spell("Invulnerability", 9, ABJ),
  Spell("Jallarzi's Storm of Radiance", 5, EVO),
  Spell("Jump", 1, TRA),
  Spell("Kinetic Jaunt", 2, TRA),
  Spell("Knock", 2, TRA),
  Spell("Legend Lore", 5, DIV),
  Spell("Leomund's Secret Chest", 4, CON),
  Spell("Leomund's Tiny Hut", 3, EVO),
  Spell("Lesser Restoration", 2, ABJ),
  Spell("Levitate", 2, TRA),
  Spell("Life Transference", 3, NEC),
  Spell("Light", 0, EVO),
  Spell("Lightning Arrow", 3, TRA),
  Spell("Lightning Bolt", 3, EVO),
  Spell("Lightning Lure", 0, EVO),
  Spell("Lightning Storm", 7, EVO),
  Spell("Lithospheric Blades", 1, TRA),
  Spell("Locate Animals or Plants", 2, DIV),
  Spell("Locate Creature", 4, DIV),
  Spell("Locate Object", 2, DIV),
  Spell("Longstrider", 1, TRA),
  Spell("Maddening Darkness", 8, EVO),
  Spell("Maelstrom", 5, EVO),
  Spell("Mage Armor", 1, ABJ),
  Spell("Mage Hand", 0, CON),
  Spell("Magic Circle", 3, ABJ),
  Spell("Magic Jar", 6, NEC),
  Spell("Magic Missile", 1, EVO),
  Spell("Magic Mouth", 2, ILL),
  Spell("Magic Stone", 0, TRA),
  Spell("Magic Weapon", 2, TRA),
  Spell("Magnify Gravity", 1, TRA),
  Spell("Major Image", 3, ILL),
  Spell("Mass Cure Wounds", 5, ABJ),
  Spell("Mass Heal", 9, ABJ),
  Spell("Mass Healing Word", 3, ABJ),
  Spell("Mass Polymorph", 9, TRA),
  Spell("Mass Suggestion", 6, ENC),
  Spell("Maximilian's Earthen Grasp", 2, TRA),
  Spell("Maze", 8, CON),
  Spell("Meld into Stone", 3, TRA),
  Spell("Melf's Acid Arrow", 2, EVO),
  Spell("Melf's Minute Meteors", 3, EVO),
  Spell("Mending", 0, TRA),
  Spell("Mental Prison", 6, ILL),
  Spell("Message", 0, TRA),
  Spell("Meteor Swarm", 9, EVO),
  Spell("Mighty Fortress", 8, CON),
  Spell("Mind Blank", 8, ABJ),
  Spell("Mind Sliver", 0, ENC),
  Spell("Mind Spike", 2, DIV),
  Spell("Minor Illusion", 0, ILL),
  Spell("Mirage Arcane", 7, ILL),
  Spell("Mirror Image", 2, ILL),
  Spell("Mislead", 5, ILL),
  Spell("Misty Step", 2, CON),
  Spell("Modify Memory", 5, ENC),
  Spell("Mold Earth", 0, TRA),
  Spell("Moonbeam", 2, EVO),
  Spell("Mordenkainen's Faithful Hound", 4, CON),
  Spell("Mordenkainen's Magnificent Mansion", 7, CON),
  Spell("Mordenkainen's Private Sanctum", 4, ABJ),
  Spell("Mordenkainen's Sword", 7, EVO),
  Spell("Move Earth", 6, TRA),
  Spell("Nathair's Mischief", 2, ILL),
  Spell("Negative Energy Flood", 5, NEC),
  Spell("Nondetection", 3, ABJ),
  Spell("Nystul's Magic Aura", 2, ILL),
  Spell("Open Communication", 4, EVO),
  Spell("Otiluke's Freezing Sphere", 6, EVO),
  Spell("Otiluke's Resilient Sphere", 4, EVO),
  Spell("Otto's Irresistible Dance", 6, ENC),
  Spell("Pass without Trace", 2, ABJ),
  Spell("Passwall", 5, TRA),
  Spell("Phantasmal Force", 2, ILL),
  Spell("Phantasmal Killer", 4, ILL),
  Spell("Phantom Steed", 3, ILL),
  Spell("Planar Ally", 6, CON),
  Spell("Planar Binding", 5, ABJ),
  Spell("Plane Shift", 7, CON),
  Spell("Plant Growth", 3, TRA),
  Spell("Poison Spray", 0, CON),
  Spell("Polymorph", 4, TRA),
  Spell("Power Word Fortify", 7, ENC),
  Spell("Power Word Heal", 9, EVO),
  Spell("Power Word Kill", 9, ENC),
  Spell("Power Word Pain", 7, ENC),
  Spell("Power Word Stun", 8, ENC),
  Spell("Prayer of Healing", 2, EVO),
  Spell("Prestidigitation", 0, TRA),
  Spell("Primal Savagery", 0, TRA),
  Spell("Primordial Ward", 6, ABJ),
  Spell("Prismatic Spray", 7, EVO),
  Spell("Prismatic Wall", 9, ABJ),
  Spell("Produce Flame", 0, CON),
  Spell("Programmed Illusion", 6, ILL),
  Spell("Project Image", 7, ILL),
  Spell("Protection from Energy", 3, ABJ),
  Spell("Protection from Evil and Good", 1, ABJ),
  Spell("Protection from Poison", 2, ABJ),
  Spell("Psychic Scream", 9, ENC),
  Spell("Pulse Wave", 3, EVO),
  Spell("Purify Food and Drink", 1, TRA),
  Spell("Pyrotechnics", 2, TRA),
  Spell("Raise Dead", 5, NEC),
  Spell("Rary's Telepathic Bond", 5, DIV),
  Spell("Raulothim's Psychic Lance", 4, ENC),
  Spell("Ravenous Void", 9, EVO),
  Spell("Ray of Enfeeblement", 2, NEC),
  Spell("Ray of Frost", 0, EVO),
  Spell("Ray of Sickness", 1, NEC),
  Spell("Reality Break", 8, CON),
  Spell("Reanimate Greater Monster", 8, NEC),
  Spell("Reanimate Lesser Monster", 6, NEC),
  Spell("Regenerate", 7, TRA),
  Spell("Reincarnate", 5, TRA),
  Spell("Remove curse", 3, ABJ),
  Spell("Resistance", 0, ABJ),
  Spell("Resurrection", 7, NEC),
  Spell("Reverse Gravity", 7, TRA),
  Spell("Revivify", 3, NEC),
  Spell("Rime's Binding Ice", 2, EVO),
  Spell("Rope Trick", 2, TRA),
  Spell("Sacred Flame", 0, EVO),
  Spell("Sanctuary", 1, ABJ),
  Spell("Sapping Sting", 0, NEC),
  Spell("Scatter", 6, CON),
  Spell("Scorching Ray", 2, EVO),
  Spell("Scrying", 5, DIV),
  Spell("Searing Smite", 1, EVO),
  Spell("See Invisibility", 2, DIV),
  Spell("Seeming", 5, ILL),
  Spell("Sending", 3, DIV),
  Spell("Sequester", 7, TRA),
  Spell("Shadow Blade", 2, ILL),
  Spell("Shadow of Moil", 4, NEC),
  Spell("Shape Water", 0, TRA),
  Spell("Shapechange", 9, TRA),
  Spell("Shatter", 2, EVO),
  Spell("Shield", 1, ABJ),
  Spell("Shield of Faith", 1, ABJ),
  Spell("Shillelagh", 0, TRA),
  Spell("Shining Smite", 2, TRA),
  Spell("Shocking Grasp", 0, EVO),
  Spell("Sickening Radiance", 4, EVO),
  Spell("Silence", 2, ILL),
  Spell("Silent Image", 1, ILL),
  Spell("Silvery Barbs", 1, ENC),
  Spell("Simulacrum", 7, ILL),
  Spell("Skill Empowerment", 5, TRA),
  Spell("Skywrite", 2, TRA),
  Spell("Sleep", 1, ENC),
  Spell("Sleet Storm", 3, CON),
  Spell("Slow", 3, TRA),
  Spell("Snare", 1, ABJ),
  Spell("Snilloc's Snowball Swarm", 2, EVO),
  Spell("Soul Cage", 6, NEC),
  Spell("Spare the Dying", 0, NEC),
  Spell("Speak with Animals", 1, DIV),
  Spell("Speak with Dead", 3, NEC),
  Spell("Speak with Plants", 3, TRA),
  Spell("Spider Climb", 2, TRA),
  Spell("Spike Growth", 2, TRA),
  Spell("Spirit Guardians", 3, CON),
  Spell("Spirit of Death", 4, NEC),
  Spell("Spirit Shroud", 3, NEC),
  Spell("Spiritual Weapon", 2, EVO),
  Spell("Spray of Cards", 2, CON),
  Spell("Staggering Smite", 4, EVO),
  Spell("Starry Wisp", 0, EVO),
  Spell("Steel Wind Strike", 5, CON),
  Spell("Stinking Cloud", 3, CON),
  Spell("Stone Shape", 4, TRA),
  Spell("Stoneskin", 4, ABJ),
  Spell("Storm of Vengeance", 9, CON),
  Spell("Storm Sphere", 4, EVO),
  Spell("Suggestion", 2, ENC),
  Spell("Summon Aberration", 4, CON),
  Spell("Summon Beast", 2, CON),
  Spell("Summon Celestial", 5, CON),
  Spell("Summon Construct", 4, CON),
  Spell("Summon Dragon", 5, CON),
  Spell("Summon Elemental", 4, CON),
  Spell("Summon Fey", 3, CON),
  Spell("Summon Fiend", 6, CON),
  Spell("Summon Greater Demon", 4, CON),
  Spell("Summon Lesser Demon", 3, CON),
  Spell("Summon Shadowspawn", 3, CON),
  Spell("Summon Undead", 3, NEC),
  Spell("Sunbeam", 6, EVO),
  Spell("Sunburst", 8, EVO),
  Spell("Swift Quiver", 5, TRA),
  Spell("Sword Burst", 0, CON),
  Spell("Symbol", 7, ABJ),
  Spell("Synaptic Static", 5, ENC),
  Spell("Tasha's Bubbling Cauldron", 6, CON),
  Spell("Tasha's Caustic Brew", 1, EVO),
  Spell("Tasha's Hideous Laughter", 1, ENC),
  Spell("Tasha's Mind Whip", 2, ENC),
  Spell("Tasha's Otherworldly Guise", 6, TRA),
  Spell("Telekinesis", 5, TRA),
  Spell("Telepathy", 8, DIV),
  Spell("Teleport", 7, CON),
  Spell("Teleportation Circle", 5, CON),
  Spell("Temple of the Gods", 7, CON),
  Spell("Temporal Shunt", 5, TRA),
  Spell("Tenser's Floating Disk", 1, CON),
  Spell("Tenser's Transformation", 6, TRA),
  Spell("Tether Essence", 7, NEC),
  Spell("Thaumaturgy", 0, TRA),
  Spell("Thorn Whip", 0, TRA),
  Spell("Thunder Step", 3, CON),
  Spell("Thunderclap", 0, EVO),
  Spell("Thunderous Smite", 1, EVO),
  Spell("Thunderwave", 1, EVO),
  Spell("Tidal Wave", 3, CON),
  Spell("Time Ravage", 9, NEC),
  Spell("Time Stop", 9, TRA),
  Spell("Tiny Servant", 3, TRA),
  Spell("Toll the Dead", 0, NEC),
  Spell("Tongues", 3, DIV),
  Spell("Transmute Rock", 5, TRA),
  Spell("Transport via Plants", 6, CON),
  Spell("Tree Stride", 5, CON),
  Spell("True Polymorph", 9, TRA),
  Spell("True Resurrection", 9, NEC),
  Spell("True Seeing", 6, DIV),
  Spell("True Strike", 0, DIV),
  Spell("Tsunami", 8, CON),
  Spell("Unseen Servant", 1, CON),
  Spell("Vampiric Touch", 3, NEC),
  Spell("Vicious Mockery", 0, ENC),
  Spell("Vitriolic Sphere", 4, EVO),
  Spell("Vortex Warp", 2, CON),
  Spell("Wall of Fire", 4, EVO),
  Spell("Wall of Force", 5, EVO),
  Spell("Wall of Ice", 6, EVO),
  Spell("Wall of Light", 5, EVO),
  Spell("Wall of Sand", 3, EVO),
  Spell("Wall of Stone", 5, EVO),
  Spell("Wall of Thorns", 6, CON),
  Spell("Wall of Water", 3, EVO),
  Spell("Warding Bond", 2, ABJ),
  Spell("Warding Wind", 2, EVO),
  Spell("Water Breathing", 3, TRA),
  Spell("Water Walk", 3, TRA),
  Spell("Watery Sphere", 4, CON),
  Spell("Web", 2, CON),
  Spell("Weird", 9, ILL),
  Spell("Whirlwind", 7, EVO),
  Spell("Wind Walk", 6, TRA),
  Spell("Wind Wall", 3, EVO),
  Spell("Wish", 9, CON),
  Spell("Witch Bolt", 1, EVO),
  Spell("Wither and Bloom", 2, NEC),
  Spell("Word of Radiance", 0, EVO),
  Spell("Word of Recall", 6, CON),
  Spell("Wrath of Nature", 5, EVO),
  Spell("Wrathful Smite", 1, EVO),
  Spell("Wristpocket", 2, CON),
  Spell("Yolande's Regal Presence", 5, TRA),
  Spell("Zephyr Strike", 1, TRA),
  Spell("Zone of Truth", 2, ENC),
]

CANTRIPS = [spell for spell in SPELLS if spell.level == 0]
FIRST = [spell for spell in SPELLS if spell.level == 1]
SECOND = [spell for spell in SPELLS if spell.level == 2]
THIRD = [spell for spell in SPELLS if spell.level == 3]
FOURTH = [spell for spell in SPELLS if spell.level == 4]
FIFTH = [spell for spell in SPELLS if spell.level == 5]
SIXTH = [spell for spell in SPELLS if spell.level == 6]
SEVENTH = [spell for spell in SPELLS if spell.level == 7]
EIGHTH = [spell for spell in SPELLS if spell.level == 8]
NINTH = [spell for spell in SPELLS if spell.level == 9]
ABJURATION = [spell for spell in SPELLS if spell.school == ABJ]
CONJURATION = [spell for spell in SPELLS if spell.school == CON]
DIVINATION = [spell for spell in SPELLS if spell.school == DIV]
ENCHANTMENT = [spell for spell in SPELLS if spell.school == ENC]
EVOCATION = [spell for spell in SPELLS if spell.school == EVO]
ILLUSION = [spell for spell in SPELLS if spell.school == ILL]
NECROMANCY = [spell for spell in SPELLS if spell.school == NEC]
TRANSMUTATION = [spell for spell in SPELLS if spell.school == TRA]

# Common: 50 - 100 gp
# Uncommon: 100 - 500 gp
# Rare: 500 - 5,000 gp
# Very Rare: 5,000 - 50,000 gp
# Legendary: 50,000+ gp

ITEMS = [
  Item("___ of Gleaming", 50, "Armor", False, "Common", MEDIUM_ARMOR + HEAVY_ARMOR),
  Item("Bead of Nourishment (30)", 50, "Consumable", False, "Common"),
  Item("Bead of Refreshment (30)", 50, "Consumable", False, "Common"),
  Item("Boots of False Tracks", 75, "Clothing", False, "Common"),
  Item("Candle of the Deep", 50, "Wondrous Item", False, "Common"),
  Item("Cast-Off ___", 75, "Armor", False, "Common", ARMOR),
  Item("Charlatan's Die", 50, "Wondrous Item", True, "Common"),
  Item("Cloak of Billowing", 50, "Clothing", False, "Common"),
  Item("Cloak of Many Fashions", 60, "Clothing", False, "Common"),
  Item("Clockwork Amulet", 75, "Jewelry", False, "Common"),
  Item("Clothes of Mending", 50, "Clothing", False, "Common"),
  Item("Coin of Delving", 80, "Jewelry", False, "Common"),
  Item("Dark Shard Amulet", 100, "Class Item", True, "Common"),
  Item("Dread Helm", 50, "Clothing", False, "Common"),
  Item("Ear Horn of Hearing", 85, "Wondrous Item", False, "Common"),
  Item("Enduring Spellbook", 60, "Wondrous Item", False, "Common"),
  Item("Ersatz Eye", 75, "Wondrous Item", False, "Common"),
  Item("Hat of Vermin", 90, "Wondrous Item", False, "Common"),
  Item("Hat of Wizardry", 100, "Class Item", True, "Common"),
  Item("Heward's Handy Spice Pouch", 75, "Wondrous Item", False, "Common"),
  Item("Horn of Silent Alarm", 75, "Wondrous Item", False, "Common"),
  Item("Illuminator's Tattoo", 90, "Tattoo", True, "Common"),
  Item("Instrument of Illusions", 75, "Wondrous Item", True, "Common"),
  Item("Instrument of Scribing", 75, "Wondrous Item", True, "Common"),
  Item("Lock of Trickery", 65, "Wondrous Item", False, "Common"),
  Item("Masquerade Tattoo", 100, "Tattoo", True, "Common"),
  Item("Moon-Touched ___", 90, "Weapon", True, "Common", SWORDS),
  Item("Mystery Key", 100, "Wondrous Item", False, "Common"),
  Item("Orb of Direction", 50, "Wondrous Item", False, "Common"),
  Item("Orb of Time", 50, "Wondrous Item", False, "Common"),
  Item("Perfume of Bewitching", 69, "Consumable", False, "Common"),
  Item("Pipe of Smoke Monsters", 55, "Wondrous Item", False, "Common"),
  Item("Pole of Angling", 50, "Wondrous Item", False, "Common"),
  Item("Pole of Collapsing", 50, "Wondrous Item", False, "Common"),
  Item("Pot of Awakening", 100, "Wondrous Item", False, "Common"),
  Item("Potion of Climbing (long rest variant)", 100, "Consumable", False, "Common"),
  Item("Potion of Comprehension", 75, "Consumable", False, "Common"),
  Item("Potion of Healing", 50, "Consumable", False, "Common"),
  Item("Prosthetic Limb", 100, "Wondrous Item", False, "Common"),
  Item("Rival Coin", 77, "Wondrous Item", False, "Common"),
  Item("Rope of Mending", 50, "Wondrous Item", False, "Common"),
  Item("Ruby of the War Mage", 100, "Wondrous Item", True, "Common"),
  Item("___ of Expression", 50, "Armor", False, "Common", SHIELDS),
  Item("Silvered ___", 10, "Weapon", False, "Common", WEAPONS),
  Item("Smoldering ___", 50, "Armor", False, "Common", ARMOR),
  Item("Spell Scroll of ___ (cantrip)", 30, "Spell Scroll", False, "Common", CANTRIPS),
  Item("Spell Scroll of ___ (1st level)", 50, "Spell Scroll", False, "Common", FIRST),
  Item("Spellwrought Tattoo of ___ (cantrip)", 40, "Tattoo", False, "Common", CANTRIPS),
  Item("Spellwrought Tattoo of ___ (1st level)", 75, "Tattoo", False, "Common", FIRST),
  Item("Staff of Adornment", 50, "Wand/Staff", False, "Common"),
  Item("Staff of Birdcalls", 50, "Wand/Staff", False, "Common"),
  Item("Staff of Flowers", 50, "Wand/Staff", False, "Common"),
  Item("Sylvan Talon ___", 100, "Weapon", True, "Common", [w for w in WEAPONS if w.name in ["Dagger", "Rapier", "Scimitar", "Shortsword", "Sickle", "Spear"]]),
  Item("Talking Doll", 70, "Wondrous Item", False, "Common"),
  Item("Tankard of Sobriety", 80, "Wondrous Item", False, "Common"),
  Item("Veteran's Cane", 100, "Weapon", False, "Common", [w for w in WEAPONS if w.name == "Longsword"]),
  Item("Vox Seeker", 100, "Wondrous Item", False, "Common"),
  Item("Wand of Conducting", 70, "Wand/Staff", False, "Common"),
  Item("Wand of Pyrotechnics", 50, "Wand/Staff", False, "Common"),
  Item("Wand of Scowls", 75, "Wand/Staff", False, "Common"),
  Item("Wand of Smiles", 75, "Wand/Staff", False, "Common"),
  Item("+1 All Purpose Tool", 350, "Class Item", True, "Uncommon"),
  Item("+1 Amulet of the Devout", 350, "Class Item", True, "Uncommon"),
  Item("+1 Arcane Grimoire", 350, "Class Item", True, "Uncommon"),
  Item("+1 Bloodwell Vial", 350, "Class Item", True, "Uncommon"),
  Item("+1 Dragonhide Belt", 300, "Class Item", True, "Uncommon"),
  Item("+1 Moon Sickle", 400, "Class Item", True, "Uncommon"),
  Item("+1 Rhythm Maker's Drum", 350, "Class Item", True, "Uncommon"),
  Item("+1 Rod of the Pact Keeper", 450, "Class Item", True, "Uncommon"),
  Item("+1 ___", 200, "Armor", False, "Uncommon", SHIELDS),
  Item("+1 Wand of the War Mage", 350, "Wand/Staff", True, "Uncommon"),
  Item("+1 ___", 250, "Weapon", False, "Uncommon", WEAPONS),
  Item("+1 Wraps of Unarmed Power", 250, "Clothing", False, "Uncommon"),
  Item("Adamantine ___", 400, "Armor", False, "Uncommon", [a for a in MEDIUM_ARMOR if a.name != "Hide"] + HEAVY_ARMOR),
  Item("Alchemy Jug", 100, "Wondrous Item", False, "Uncommon"),
  Item("Amulet of Proof against Detection and Location", 200, "Jewelry", True, "Uncommon"),
  Item("Amulet of the Drunkard", 250, "Jewelry", False, "Uncommon"),
  Item("___ of Fungal Spores", 150, "Armor", False, "Uncommon", MEDIUM_ARMOR),
  Item("___ of the Fallen", 300, "Armor", True, "Uncommon", MEDIUM_ARMOR + HEAVY_ARMOR),
  Item("___ of Weightlessness", 250, "Armor", True, "Uncommon", ARMOR),
  Item("Bag of Holding", 75, "Wondrous Item", False, "Uncommon"),
  Item("Gray Bag of Tricks", 200, "Wondrous Item", False, "Uncommon"),
  Item("Rust Bag of Tricks", 300, "Wondrous Item", False, "Uncommon"),
  Item("Tan Bag of Tricks", 175, "Wondrous Item", False, "Uncommon"),
  Item("Barrier Tattoo (Uncommon)", 180, "Tattoo", True, "Uncommon"),
  Item("Blasted Goggles", 200, "Wondrous Item", True, "Uncommon"),
  Item("Bloodrage ___", 250, "Weapon", False, "Uncommon", [w for w in WEAPONS if w.name == "Greataxe"]),
  Item("Boomerang ___", 180, "Armor", True, "Uncommon", SHIELDS),
  Item("Boots of Elvenkind", 200, "Clothing", False, "Uncommon"),
  Item("Boots of Striding and Springing", 150, "Clothing", True, "Uncommon"),
  Item("Boots of the Winterlands", 400, "Clothing", True, "Uncommon"),
  Item("Bracers of Archery", 400, "Clothing", True, "Uncommon"),
  Item("Brooch of Living Essence", 160, "Jewelry", True, "Uncommon"),
  Item("Brooch of Shielding", 360, "Jewelry", True, "Uncommon"),
  Item("Broom of Flying", 125, "Wondrous Item", False, "Uncommon"),
  Item("Cap of Waterbreathing", 220, "Clothing", False, "Uncommon"),
  Item("Card Sharp's Deck", 280, "Wondrous Item", False, "Uncommon"),
  Item("Circlet of Blasting", 210, "Jewelry", False, "Uncommon"),
  Item("Cloak of Elvenkind", 350, "Clothing", True, "Uncommon"),
  Item("Cloak of Protection", 400, "Clothing", True, "Uncommon"),
  Item("Cloak of the Manta Ray", 420, "Clothing", False, "Uncommon"),
  Item("Coiling Grasp Tattoo", 250, "Tattoo", True, "Uncommon"),
  Item("Decanter of Endless Water", 120, "Wondrous Item", False, "Uncommon"),
  Item("Deck of Illusions", 400, "Wondrous Item", False, "Uncommon"),
  Item("Deck of Miscellany", 300, "Wondrous Item", False, "Uncommon"),
  Item("Deck of Wonder", 500, "Wondrous Item", False, "Uncommon"),
  Item("Defender's Prayer Beads", 500, "Wondrous Item", True, "Uncommon"),
  Item("Doss Lute", 400, "Class Item", True, "Uncommon"),
  Item("Dragon Vessel (Slumbering)", 450, "Wondrous Item", True, "Uncommon"),
  Item("Dragon's Wrath ___ (Slumbering)", 150, "Weapon", True, "Uncommon", WEAPONS),
  Item("Dragon-Touched Focus (Slumbering)", 250, "Wondrous Item", True, "Uncommon"),
  Item("Driftglobe", 200, "Wondrous Item", False, "Uncommon"),
  Item("Dust of Deliciousness", 220, "Consumable", False, "Uncommon"),
  Item("Dust of Disappearance", 100, "Consumable", False, "Uncommon"),
  Item("Dust of Dryness", 150, "Consumable", False, "Uncommon"),
  Item("Dust of Sneezing and Choking", 80, "Consumable", False, "Uncommon"),
  Item("Eldritch Claw Tattoo", 450, "Tattoo", True, "Uncommon"),
  Item("Elemental Gem (Blue Sapphire)", 400, "Wondrous Item", False, "Uncommon"),
  Item("Elemental Gem (Yellow Diamond)", 400, "Wondrous Item", False, "Uncommon"),
  Item("Elemental Gem (Red Corundum)", 400, "Wondrous Item", False, "Uncommon"),
  Item("Elemental Gem (Emerald)", 400, "Wondrous Item", False, "Uncommon"),
  Item("Emerald Pen", 240, "Wondrous Item", False, "Uncommon"),
  Item("Etherstone Cuffs", 230, "Jewelry", False, "Uncommon"),
  Item("Eversmoking Bottle", 300, "Wondrous Item", False, "Uncommon"),
  Item("Eyes of Charming", 190, "Wondrous Item", True, "Uncommon"),
  Item("Eyes of Minute Seeing", 260, "Wondrous Item", False, "Uncommon"),
  Item("Eyes of the Eagle", 350, "Wondrous Item", True, "Uncommon"),
  Item("Fabulist Gem", 410, "Jewelry", True, "Uncommon"),
  Item("Feywild Shard", 320, "Class Item", True, "Uncommon"),
  Item("Figurine of Wondrous Power (Silver Raven)", 250, "Wondrous Item", False, "Uncommon"),
  Item("Flux Stone (acid)", 500, "Wondrous Item", True, "Uncommon"),
  Item("Flux Stone (cold)", 500, "Wondrous Item", True, "Uncommon"),
  Item("Flux Stone (fire)", 500, "Wondrous Item", True, "Uncommon"),
  Item("Flux Stone (lightning)", 500, "Wondrous Item", True, "Uncommon"),
  Item("Flux Stone (poison)", 500, "Wondrous Item", True, "Uncommon"),
  Item("Flux Stone (thunder)", 500, "Wondrous Item", True, "Uncommon"),
  Item("Fochlucan Bandore", 400, "Class Item", True, "Uncommon"),
  Item("Gauntlets of Ogre Power", 450, "Clothing", True, "Uncommon"),
  Item("Gem of Brightness", 370, "Wondrous Item", False, "Uncommon"),
  Item("Gloves of Missile Snaring", 300, "Clothing", True, "Uncommon"),
  Item("Gloves of Swimming and Climbing", 220, "Clothing", False, "Uncommon"),
  Item("Gloves of Thievery", 250, "Clothing", False, "Uncommon"),
  Item("Goggles of Night", 180, "Clothing", False, "Uncommon"),
  Item("Goggles of Object Reading", 300, "Clothing", True, "Uncommon"),
  Item("Guardian Emblem", 300, "Wondrous Item", True, "Uncommon"),
  Item("Hat of Disguise", 250, "Clothing", True, "Uncommon"),
  Item("Headband of Intellect", 450, "Clothing", True, "Uncommon"),
  Item("Helm of Comprehending Languages", 330, "Clothing", False, "Uncommon"),
  Item("Helm of Telepathy", 340, "Clothing", True, "Uncommon"),
  Item("House of Cards", 260, "Wondrous Item", False, "Uncommon"),
  Item("Immovable Rod", 280, "Wondrous Item", False, "Uncommon"),
  Item("___ of Lightning", 410, "Weapon", False, "Uncommon", SPEARS),
  Item("Keoghtom's Ointment", 400, "Consumable", False, "Uncommon"),
  Item("Lantern of Revealing", 240, "Wondrous Item", False, "Uncommon"),
  Item("Leomund's Persistent Tent", 500, "Wondrous Item", False, "Uncommon"),
  Item("Mac-Fuirmidh Cittern", 400, "Class Item", True, "Uncommon"),
  Item("Mariner's ___", 300, "Armor", False, "Uncommon", ARMOR),
  Item("Medallion of Thoughts", 200, "Jewelry", True, "Uncommon"),
  Item("Mind Carapace __", 500, "Armor", True, "Uncommon", HEAVY_ARMOR),
  Item("Mithral ___", 250, "Armor", False, "Uncommon", [a for a in MEDIUM_ARMOR if a.name != "Hide"] + HEAVY_ARMOR),
  Item("Nature's Mantle", 250, "Clothing", True, "Uncommon"),
  Item("Necklace of Adaptation", 330, "Jewelry", True, "Uncommon"),
  Item("Oil of Slipperiness", 100, "Consumable", False, "Uncommon"),
  Item("Pearl of Power", 380, "Wondrous Item", True, "Uncommon"),
  Item("Periapt of Health", 280, "Jewelry", False, "Uncommon"),
  Item("Periapt of Wound Closure", 320, "Jewelry", False, "Uncommon"),
  Item("Philter of Love", 340, "Consumable", False, "Uncommon"),
  Item("Pipes of Haunting", 390, "Wondrous Item", False, "Uncommon"),
  Item("Pipes of the Sewers", 240, "Wondrous Item", True, "Uncommon"),
  Item("___ of Knight's Fellowship", 500, "Armor", True, "Uncommon", PLATE),
  Item("Potion of Animal Friendship (long rest variant)", 150, "Consumable", False, "Uncommon"),
  Item("Potion of Fire Breath (long rest variant)", 200, "Consumable", False, "Uncommon"),
  Item("Potion of Hill Giant Strength (long rest variant)", 450, "Consumable", False, "Uncommon"),
  Item("Potion of Growth (long rest variant)", 250, "Consumable", False, "Uncommon"),
  Item("Potion of Healing (Greater)", 120, "Consumable", False, "Uncommon"),
  Item("Potion of Poison", 50, "Consumable", False, "Uncommon"),
  Item("Potion of Pugilism", 300, "Consumable", False, "Uncommon"),
  Item("Potion of Acid Resistance (long rest variant)", 270, "Consumable", False, "Uncommon"),
  Item("Potion of Cold Resistance (long rest variant)", 270, "Consumable", False, "Uncommon"),
  Item("Potion of Fire Resistance (long rest variant)", 270, "Consumable", False, "Uncommon"),
  Item("Potion of Force Resistance (long rest variant)", 270, "Consumable", False, "Uncommon"),
  Item("Potion of Lightning Resistance (long rest variant)", 270, "Consumable", False, "Uncommon"),
  Item("Potion of Necrotic Resistance (long rest variant)", 270, "Consumable", False, "Uncommon"),
  Item("Potion of Poison Resistance (long rest variant)", 270, "Consumable", False, "Uncommon"),
  Item("Potion of Psychic Resistance (long rest variant)", 270, "Consumable", False, "Uncommon"),
  Item("Potion of Radiant Resistance (long rest variant)", 270, "Consumable", False, "Uncommon"),
  Item("Potion of Thunder Resistance (long rest variant)", 270, "Consumable", False, "Uncommon"),
  Item("Potion of Water Breathing (long rest variant)", 100, "Consumable", False, "Uncommon"),
  Item("Figurine of Wondrous Power (Pyrite Plesiosaurus)", 430, "Wondrous Item", False, "Uncommon"),
  Item("Quiver of Ehlonna", 200, "Wondrous Item", False, "Uncommon"),
  Item("Ring of Jumping", 150, "Jewelry", True, "Uncommon"),
  Item("Ring of Mind Shielding", 300, "Jewelry", True, "Uncommon"),
  Item("Ring of Obscuring", 230, "Jewelry", True, "Uncommon"),
  Item("Ring of Puzzler's Wit", 180, "Jewelry", False, "Uncommon"),
  Item("Ring of Swimming", 200, "Jewelry", False, "Uncommon"),
  Item("Ring of Warmth", 320, "Jewelry", True, "Uncommon"),
  Item("Ring of Water Walking", 170, "Jewelry", False, "Uncommon"),
  Item("Robe of Useful Items", 380, "Clothing", False, "Uncommon"),
  Item("Rod of Retribution", 350, "Wondrous Item", True, "Uncommon"),
  Item("Rope of Climbing", 220, "Wondrous Item", False, "Uncommon"),
  Item("Saddle of the Cavalier", 400, "Wondrous Item", False, "Uncommon"),
  Item("Scaled Ornament (Slumbering)", 290, "Jewelry", True, "Uncommon"),
  Item("Sending Stones (Improved)", 300, "Wondrous Item", False, "Uncommon"),
  Item("Sentinel ___", 360, "Armor", False, "Uncommon", SHIELDS),
  Item("___ of the Tortoise", 150, "Armor", True, "Uncommon", SHIELDS),
  Item("___ of Giant Felling", 240, "Weapon", False, "Uncommon", [w for w in WEAPONS if w.name == "Sling"]),
  Item("Slippers of Spider Climbing", 300, "Clothing", True, "Uncommon"),
  Item("Spell Scroll of ___ (2nd level)", 200, "Spell Scroll", False, "Uncommon", SECOND),
  Item("Spell Scroll of ___ (3rd level)", 300, "Spell Scroll", False, "Uncommon", THIRD),
  Item("Spellwrought Tattoo of ___ (2nd level)", 150, "Tattoo", False, "Uncommon", SECOND),
  Item("Spellwrought Tattoo of ___ (3rd level)", 300, "Tattoo", False, "Uncommon", THIRD),
  Item("Staff of the Adder", 260, "Wand/Staff", True, "Uncommon"),
  Item("Staff of the Python", 480, "Wand/Staff", True, "Uncommon"),
  Item("Stone of Good Luck", 400, "Wondrous Item", True, "Uncommon"),
  Item("___ of Vengeance", 200, "Weapon", True, "Uncommon", SWORDS),
  Item("___ of Fish Command", 400, "Weapon", True, "Uncommon", [w for w in WEAPONS if w.name == "Trident"]),
  Item("Wand of Brilliance", 420, "Wand/Staff", False, "Uncommon"),
  Item("Wand of Magic Detection", 100, "Wand/Staff", False, "Uncommon"),
  Item("Wand of Magic Missiles", 280, "Wand/Staff", False, "Uncommon"),
  Item("Wand of Secrets", 100, "Wand/Staff", False, "Uncommon"),
  Item("Wand of Web", 250, "Wand/Staff", True, "Uncommon"),
  Item("___ of Warning", 500, "Weapon", True, "Uncommon", WEAPONS),
  Item("Wind Fan", 150, "Wondrous Item", False, "Uncommon"),
  Item("Winged Boots", 300, "Clothing", True, "Uncommon"),
  Item("Acheron ___", 800, "Weapon", True, "Rare", SWORDS),
  Item("Alchemical Compendium", 1200, "Class Item", True, "Rare"),
  Item("+2 All Purpose Tool", 1500, "Class Item", True, "Rare"),
  Item("+2 Amulet of the Devout", 1200, "Class Item", True, "Rare"),
  Item("+2 Arcane Grimoire", 1200, "Class Item", True, "Rare"),
  Item("+2 Bloodwell Vial", 1200, "Class Item", True, "Rare"),
  Item("+2 Cloak of Protection", 1400, "Clothing", True, "Rare"),
  Item("+2 Dragonhide Belt", 1000, "Class Item", True, "Rare"),
  Item("+1 Fate Dealer's Deck", 1850, "Class Item", True, "Rare"),
  Item("+2 Moon Sickle", 1400, "Class Item", True, "Rare"),
  Item("+2 Rhythm Maker's Drum", 1200, "Class Item", True, "Rare"),
  Item("+2 Rod of the Pact Keeper", 1500, "Class Item", True, "Rare"),
  Item("+2 ___", 1000, "Armor", False, "Rare", SHIELDS),
  Item("+1 ___", 1500, "Armor", False, "Rare", ARMOR),
  Item("+2 Wand of the War Mage", 1200, "Wand/Staff", True, "Rare"),
  Item("+2 ___", 1200, "Weapon", False, "Rare", WEAPONS),
  Item("+2 Wraps of Unarmed Power", 1000, "Clothing", False, "Rare"),
  Item("Amulet of Health", 2000, "Jewelry", True, "Rare"),
  Item("___ of Acid Resistance", 1500, "Armor", True, "Rare", ARMOR),
  Item("___ of Cold Resistance", 1500, "Armor", True, "Rare", ARMOR),
  Item("___ of Fire Resistance", 1500, "Armor", True, "Rare", ARMOR),
  Item("___ of Force Resistance", 1500, "Armor", True, "Rare", ARMOR),
  Item("___ of Lightning Resistance", 1500, "Armor", True, "Rare", ARMOR),
  Item("___ of Necrotic Resistance", 1500, "Armor", True, "Rare", ARMOR),
  Item("___ of Poison Resistance", 1500, "Armor", True, "Rare", ARMOR),
  Item("___ of Psychic Resistance", 1500, "Armor", True, "Rare", ARMOR),
  Item("___ of Radiant Resistance", 1500, "Armor", True, "Rare", ARMOR),
  Item("___ of Thunder Resistance", 1500, "Armor", True, "Rare", ARMOR),
  Item("___ of Vulnerability (Bludgeoning)", 500, "Armor", True, "Rare", PLATE),
  Item("___ of Vulnerability (Piercing)", 500, "Armor", True, "Rare", PLATE),
  Item("___ of Vulnerability (Slashing)", 500, "Armor", True, "Rare", PLATE),
  Item("Arrow-Catching ___", 1400, "Armor", True, "Rare", SHIELDS),
  Item("Astral Shard", 600, "Class Item", True, "Rare"),
  Item("Astromancy Archive", 2500, "Class Item", True, "Rare"),
  Item("Atlas of Endless Horizons", 2500, "Class Item", True, "Rare"),
  Item("Bag of Beans", 1800, "Wondrous Item", False, "Rare"),
  Item("Barrier Tattoo (Rare)", 3000, "Tattoo", True, "Rare"),
  Item("Battering __", 800, "Armor", True, "Rare", SHIELDS),
  Item("Bead of Force", 500, "Wondrous Item", False, "Rare"),
  Item("Bell Branch", 500, "Class Item", True, "Rare"),
  Item("Belt of Dwarven Kind", 2200, "Clothing", True, "Rare"),
  Item("Belt of Hill Giant Strength", 4000, "Clothing", True, "Rare"),
  Item("Berserker ___", 500, "Weapon", True, "Rare", AXES),
  Item("Bone Chimes of Antipathy", 5000, "Wondrous Item", True, "Rare"),
  Item("Boots of Levitation", 1300, "Clothing", True, "Rare"),
  Item("Boots of Speed", 1700, "Clothing", True, "Rare"),
  Item("___ of Conflagration", 2100, "Weapon", True, "Rare", BOWS),
  Item("Bowl of Commanding Water Elementals", 1400, "Wondrous Item", False, "Rare"),
  Item("Bracers of Defense", 1000, "Clothing", True, "Rare"),
  Item("Brazier of Commanding Fire Elementals", 1400, "Wondrous Item", False, "Rare"),
  Item("Breastplate of Balance", 1750, "Armor", True, "Rare", [w for w in ARMOR if w.name == "Breastplate"]),
  Item("Butcher's Bib", 800, "Clothing", True, "Rare"),
  Item("Cape of the Mountebank", 750, "Clothing", False, "Rare"),
  Item("Carcosa Steel ___", 2750, "Weapon", False, "Rare", [w for w in MELEE_WEAPONS if w.dtype != B]),
  Item("Censer of Controlling Air Elementals", 1400, "Wondrous Item", False, "Rare"),
  Item("Chain Dagger", 4500, "Weapon", True, "Rare", DAGGER),
  Item("Chime of Opening", 1000, "Wondrous Item", False, "Rare"),
  Item("Cloak of Displacement", 3000, "Clothing", True, "Rare"),
  Item("Cloak of the Bat", 2100, "Clothing", True, "Rare"),
  Item("Cloak of the Mist", 2100, "Clothing", True, "Rare"),
  Item("Corpse Slayer ___", 750, "Weapon", True, "Rare", WEAPONS),
  Item("Crown of the Wrath Bringer", 1100, "Jewelry", True, "Rare"),
  Item("Crystal ___", 1850, "Weapon", True, "Rare", SWORDS),
  Item("Cube of Force", 2500, "Wondrous Item", True, "Rare"),
  Item("Cube of Summoning", 2300, "Wondrous Item", False, "Rare"),
  Item("Daern's Instant Fortress", 4000, "Wondrous Item", False, "Rare"),
  Item("Dagger of Lightning", 2500, "Weapon", False, "Rare", DAGGER),
  Item("Dagger of Venom", 500, "Weapon", False, "Rare", DAGGER),
  Item("Deck of Oracles", 2000, "Wondrous Item", True, "Rare"),
  Item("Delver's Claws", 1700, "Clothing", True, "Rare"),
  Item("Devotee's Censer", 1800, "Weapon", True, "Rare", [w for w in WEAPONS if w.name == "Flail"]),
  Item("Dimensional Shackles", 1300, "Wondrous Item", False, "Rare"),
  Item("Donjon's Sundering Sphere", 1650, "Wondrous Item", True, "Rare"),
  Item("Dragon Slayer ___", 2000, "Weapon", False, "Rare", SWORDS),
  Item("Dragon Vessel (Stirring)", 1550, "Wondrous Item", True, "Rare"),
  Item("Dragon Wing ___", 3600, "Weapon", True, "Rare", BOWS),
  Item("Dragon's Wrath ___ (Stirring)", 4000, "Weapon", True, "Rare", WEAPONS),
  Item("Dragon-Touched Focus (Stirring)", 3800, "Wondrous Item", True, "Rare"),
  Item("Duplicitous Manuscript", 1800, "Class Item", True, "Rare"),
  Item("Air Elemental Essence Shard", 800, "Class Item", True, "Rare"),
  Item("Earth Elemental Essence Shard", 800, "Class Item", True, "Rare"),
  Item("Fire Elemental Essence Shard", 800, "Class Item", True, "Rare"),
  Item("Water Elemental Essence Shard", 800, "Class Item", True, "Rare"),
  Item("Elixir of Health", 650, "Consumable", False, "Rare"),
  Item("Elven Chain", 1800, "Armor", False, "Rare", [a for a in ARMOR if a.name == "Chain Shirt" or a.name == "Chain Mail"]),
  Item("Etherstone Boots", 1800, "Clothing", True, "Rare"), 
  Item("Far Realm Shard", 1400, "Class Item", True, "Rare"),
  Item("Anchor Feather Token", 300, "Wondrous Item", False, "Rare"),
  Item("Bird Feather Token", 900, "Wondrous Item", False, "Rare"),
  Item("Fan Feather Token", 500, "Wondrous Item", False, "Rare"),
  Item("Swan Boat Feather Token", 250, "Wondrous Item", False, "Rare"),
  Item("Tree Feather Token", 100, "Wondrous Item", False, "Rare"),
  Item("Whip Feather Token", 1000, "Wondrous Item", False, "Rare"),
  Item("Feywrought ___", 800, "Armor", True, "Rare", ARMOR),
  Item("Figurine of Wondrous Power (Bronze Griffon)", 1900, "Wondrous Item", False, "Rare"),
  Item("Figurine of Wondrous Power (Ebony Fly)", 800, "Wondrous Item", False, "Rare"),
  Item("Figurine of Wondrous Power (Golden Lions)", 1200, "Wondrous Item", False, "Rare"),
  Item("Figurine of Wondrous Power (Ivory Goats)", 2300, "Wondrous Item", False, "Rare"),
  Item("Figurine of Wondrous Power (Marble Elephant)", 2200, "Wondrous Item", False, "Rare"),
  Item("Figurine of Wondrous Power (Onyx Dog)", 1600, "Wondrous Item", False, "Rare"),
  Item("Figurine of Wondrous Power (Serpentine Owl)", 1100, "Wondrous Item", False, "Rare"),
  Item("Flame Tongue ___", 2700, "Weapon", True, "Rare", MELEE_WEAPONS),
  Item("Flux Stone (force)", 1500, "Wondrous Item", True, "Rare"),
  Item("Flux Stone (necrotic)", 1500, "Wondrous Item", True, "Rare"),
  Item("Flux Stone (psychic)", 1500, "Wondrous Item", True, "Rare"),
  Item("Flux Stone (radiant)", 1500, "Wondrous Item", True, "Rare"),
  Item("Flux Stone (healing)", 1500, "Wondrous Item", True, "Rare"),
  Item("Folding Boat", 1750, "Wondrous Item", False, "Rare"),
  Item("Fulminating Treatise", 2250, "Class Item", True, "Rare"),
  Item("Gauntlets of Flaming Fury", 1350, "Clothing", True, "Rare"),
  Item("Gem of Seeing", 1500, "Jewelry", True, "Rare"),
  Item("Giant Slayer ___", 1200, "Weapon", False, "Rare", SWORDS + AXES),
  Item("Glamoured ___", 1800, "Armor", False, "Rare", [a for a in ARMOR if a.name == "Studded Leather"]),
  Item("Glimmering Moonbow ___", 4200, "Weapon", True, "Rare", BOWS),
  Item("Gloomwrought ___", 800, "Armor", True, "Rare", ARMOR),
  Item("Glowrune Pigment", 600, "Consumable", False, "Rare"),
  Item("Grasping ___", 500, "Weapon", False, "Rare", [w for w in WEAPONS if w.name == "Whip"]),
  Item("Heart Weaver's Primer", 2300, "Class Item", True, "Rare"),
  Item("Helm of Teleportation", 1800, "Clothing", True, "Rare"),
  Item("Heward's Handy Haversack", 500, "Wondrous Item", False, "Rare"),
  Item("Horn of Blasting", 1700, "Wondrous Item", False, "Rare"),
  Item("Silver Horn of Valhalla", 2000, "Wondrous Item", False, "Rare"),
  Item("Brass Horn of Valhalla", 3000, "Wondrous Item", False, "Rare"),
  Item("Horseshoes of Speed", 900, "Wondrous Item", False, "Rare"),
  Item("Canaith Mandolin", 2000, "Class Item", True, "Rare"),
  Item("Cli Lyre", 2100, "Class Item", True, "Rare"),
  Item("Ioun Stone of Agility", 600, "Jewelry", True, "Rare"),
  Item("Ioun Stone of Protection", 1100, "Jewelry", True, "Rare"),
  Item("Ioun Stone of Reserve", 1400, "Jewelry", True, "Rare"),
  Item("Ioun Stone of Sustenance", 950, "Jewelry", True, "Rare"),
  # Item("Ioun Stone of Supreme Intellect", 1100, "Jewelry", True, "Rare"), these are now commented out because I don't have access to them on dnd beyond
  # Item("Ioun Stone of Historical Knowledge", 1000, "Jewelry", True, "Rare"),
  # Item("Ioun Stone of Natural Knowledge", 1000, "Jewelry", True, "Rare"),
  # Item("Ioun Stone of Religious Knowledge", 1000, "Jewelry", True, "Rare"),
  # Item("Ioun Stone of Language Knowledge", 1000, "Jewelry", True, "Rare"),
  # Item("Ioun Stone of Self-Preservation", 1300, "Jewelry", True, "Rare"),
  Item("Iron Bands of Binding", 1500, "Wondrous Item", False, "Rare"),
  Item("Lash of Immolation", 1800, "Weapon", False, "Rare", [w for w in WEAPONS if w.name == "Whip"]),
  Item("Libram of Souls and Flesh", 2300, "Class Item", True, "Rare"),
  Item("Lyre of Building", 2000, "Class Item", True, "Rare"),
  Item("Mace of Disruption", 1700, "Weapon", True, "Rare", MACE),
  Item("Mace of Smiting", 1200, "Weapon", False, "Rare", MACE),
  Item("Mace of Terror", 1750, "Weapon", True, "Rare", MACE),
  Item("Magic Bane Tattoo", 1850, "Tattoo", True, "Rare"),
  Item("Mantle of Spell Resistance", 1300, "Clothing", True, "Rare"),
  Item("+2 Moon Sickle", 1600, "Class Item", True, "Rare"),
  Item("Necklace of Fireballs", 2150, "Jewelry", False, "Rare"),
  Item("Necklace of Prayer Beads", 3000, "Jewelry", True, "Rare"),
  Item("Needle of Mending", 750, "Weapon", True, "Rare", DAGGER),
  Item("Oil of Etherealness", 1600, "Consumable", False, "Rare"),
  Item("Outer Essence Shard, Chaotic", 800, "Class Item", True, "Rare"),
  Item("Outer Essence Shard, Evil", 1800, "Class Item", True, "Rare"),
  Item("Outer Essence Shard, Good", 1800, "Class Item", True, "Rare"),
  Item("Outer Essence Shard, Lawful", 1400, "Class Item", True, "Rare"),
  Item("Periapt of Proof against Poison", 2700, "Jewelry", True, "Rare"),
  Item("Planecaller's Codex", 3000, "Class Item", True, "Rare"),
  Item("Portable Hole", 750, "Wondrous Item", False, "Rare"),
  Item("Potion of Clairvoyance", 450, "Consumable", False, "Rare"),
  Item("Potion of Diminution (long rest variant)", 650, "Consumable", False, "Rare"),
  Item("Potion of Gaseous Form (long rest variant)", 1200, "Consumable", False, "Rare"),
  Item("Potion of Frost Giant Strength (long rest variant)", 2000, "Consumable", False, "Rare"),
  Item("Potion of Stone Giant Strength (long rest variant)", 2000, "Consumable", False, "Rare"),
  Item("Potion of Fire Giant Strength (long rest variant)", 3600, "Consumable", False, "Rare"),
  Item("Potion of Heroism (long rest variant)", 1600, "Consumable", False, "Rare"),
  Item("Potion of Invisibility", 750, "Consumable", False, "Rare"),
  Item("Potion of Invulnerability", 1000, "Consumable", False, "Rare"),
  Item("Potion of Maximum Power", 750, "Consumable", False, "Rare"),
  Item("Potion of Mind Reading", 400, "Consumable", False, "Rare"),
  Item("Potion of Healing (Superior)", 300, "Consumable", False, "Rare"),
  Item("Figurine of Wondrous Power (Kyanite Pteranodon)", 850, "Wondrous Item", False, "Rare"),
  Item("Protective Verses", 2500, "Class Item", True, "Rare"),
  Item("Reveler's Concertina", 1800, "Class Item", True, "Rare"),
  Item("Ring of Animal Influence", 1250, "Jewelry", False, "Rare"),
  Item("Ring of Cooling", 650, "Jewelry", False, "Rare"),
  Item("Ring of Evasion", 1250, "Jewelry", True, "Rare"),
  Item("Ring of Feather Falling", 600, "Jewelry", True, "Rare"),
  Item("Ring of Free Action", 1600, "Jewelry", True, "Rare"),
  Item("Ring of Protection", 900, "Jewelry", True, "Rare"),
  Item("Ring of Acid Resistance", 1700, "Jewelry", False, "Rare"),
  Item("Ring of Cold Resistance", 1700, "Jewelry", False, "Rare"),
  Item("Ring of Fire Resistance", 1700, "Jewelry", False, "Rare"),
  Item("Ring of Force Resistance", 4000, "Jewelry", False, "Rare"),
  Item("Ring of Lightning Resistance", 1700, "Jewelry", False, "Rare"),
  Item("Ring of Necrotic Resistance", 3100, "Jewelry", False, "Rare"),
  Item("Ring of Poison Resistance", 1300, "Jewelry", False, "Rare"),
  Item("Ring of Psychic Resistance", 3100, "Jewelry", False, "Rare"),
  Item("Ring of Radiant Resistance", 3100, "Jewelry", False, "Rare"),
  Item("Ring of Thunder Resistance", 1700, "Jewelry", False, "Rare"),
  Item("Ring of Second Chances", 1850, "Jewelry", False, "Rare"),
  Item("Ring of Spell Storing", 1450, "Jewelry", True, "Rare"),
  Item("Ring of Temporal Salvation", 3000, "Jewelry", True, "Rare"),
  Item("Ring of the Ram", 1650, "Jewelry", True, "Rare"),
  Item("Ring of X-ray Vision", 700, "Jewelry", True, "Rare"),
  Item("Robe of Eyes", 1950, "Clothing", True, "Rare"),
  Item("Rod of Rulership", 2400, "Wondrous Item", True, "Rare"),
  Item("Rogue's Mantle", 2700, "Clothing", True, "Rare"),
  Item("Rope of Entanglement", 1200, "Wondrous Item", False, "Rare"),
  Item("Ruinous Flail", 2100, "Weapon", True, "Rare", [w for w in WEAPONS if w.name == "Flail"]),
  Item("Sage's Signet (Serpent)", 1300, "Jewelry", True, "Rare"),
  Item("Sage's Signet (Songbird)", 1300, "Jewelry", True, "Rare"),
  Item("Scaled Ornament (Stirring)", 2400, "Jewelry", True, "Rare"),
  Item("Scroll of Protection from Aberrations", 1000, "Wondrous Item", False, "Rare"),
  Item("Scroll of Protection from Beasts", 1000, "Wondrous Item", False, "Rare"),
  Item("Scroll of Protection from Celestials", 1000, "Wondrous Item", False, "Rare"),
  Item("Scroll of Protection from Elementals", 1000, "Wondrous Item", False, "Rare"),
  Item("Scroll of Protection from Fey", 1000, "Wondrous Item", False, "Rare"),
  Item("Scroll of Protection from Fiends", 1000, "Wondrous Item", False, "Rare"),
  Item("Scroll of Protection from Plants", 1000, "Wondrous Item", False, "Rare"),
  Item("Scroll of Protection from Undead", 1000, "Wondrous Item", False, "Rare"),
  Item("Shadowfell Brand Tattoo", 850, "Tattoo", True, "Rare"),
  Item("Shadowfell Shard", 1500, "Class Item", True, "Rare"),
  Item("Shield of Missile Attraction", 2200, "Armor", True, "Rare", SHIELDS),
  Item("Shrieking Greaves", 1700, "Clothing", True, "Rare"),
  Item("Spellbane Iron ___", 2750, "Weapon", False, "Rare", [w for w in MELEE_WEAPONS if w.dtype != B]),
  Item("Spell Scroll of ___ (4th level)", 2000, "Spell Scroll", False, "Rare", FOURTH),
  Item("Spell Scroll of ___ (5th level)", 3000, "Spell Scroll", False, "Rare", FIFTH),
  Item("Spellwrought Tattoo of ___ (4th level)", 600, "Tattoo", False, "Rare", FOURTH),
  Item("Spellwrought Tattoo of ___ (5th level)", 1200, "Tattoo", False, "Rare", FIFTH),
  Item("Staff of Charming", 1800, "Wand/Staff", True, "Rare"),
  Item("Staff of Healing", 2700, "Wand/Staff", True, "Rare"),
  Item("Staff of Swarming Insects", 1800, "Wand/Staff", True, "Rare"),
  Item("Staff of the Ivory Claw", 800, "Wand/Staff", True, "Rare"),
  Item("Staff of the Rooted Hills", 1100, "Wand/Staff", True, "Rare"),
  Item("Staff of the Woodlands", 4500, "Wand/Staff", True, "Rare"),
  Item("Staff of Withering", 1300, "Wand/Staff", True, "Rare"),
  Item("Starshot ___", 2500, "Weapon", True, "Rare", CROSSBOWS),
  Item("Stone of Controlling Earth Elementals", 2400, "Wondrous Item", False, "Rare"),
  Item("Sunblade", 3600, "Weapon", True, "Rare", [w for w in WEAPONS if w.name == "Longsword"]),
  Item("Sun Staff", 2800, "Wand/Staff", True, "Rare"),
  Item("___ of Life Stealing", 900, "Weapon", True, "Rare", SWORDS),
  Item("___ of Wounding", 3700, "Weapon", True, "Rare", [w for w in WEAPONS if w.wclass == "Sword" or w.name == "Glaive"]),
  Item("Tentacle Rod", 2300, "Wondrous Item", True, "Rare"),
  Item("Vicious ___", 1550, "Weapon", False, "Rare", WEAPONS),
  Item("Voidwalker Armor", 800, "Armor", True, "Rare", [a for a in ARMOR if a.name == "Studded Leather"]),
  Item("Wand of Binding", 1850, "Wand/Staff", True, "Rare"),
  Item("Wand of Enemy Detection", 650, "Wand/Staff", True, "Rare"),
  Item("Wand of Fear", 1700, "Wand/Staff", True, "Rare"),
  Item("Wand of Fireballs", 1800, "Wand/Staff", True, "Rare"),
  Item("Wand of Lightning Bolts", 1800, "Wand/Staff", True, "Rare"),
  Item("Wand of Paralysis", 2100, "Wand/Staff", True, "Rare"),
  Item("Wand of Wonder", 2442, "Wand/Staff", True, "Rare"),
  Item("War Horn of Valor", 650, "Wondrous Item", False, "Rare"),
  Item("Warrior's Passkey", 2400, "Weapon", True, "Rare", [w for w in WEAPONS if w.name == "Longsword"]),
  Item("Wayfarer's Boots", 1400, "Clothing", True, "Rare"),
  Item("___ of Certain Death", 1300, "Weapon", False, "Rare", WEAPONS),
  Item("Wings of Flying", 1500, "Clothing", True, "Rare"),
  Item("Zephyr ___", 1700, "Armor", True, "Rare", LIGHT_ARMOR),
  Item("Absorbing Tattoo, Acid", 5200, "Tattoo", True, "Very Rare"),
  Item("Absorbing Tattoo, Cold", 5200, "Tattoo", True, "Very Rare"),
  Item("Absorbing Tattoo, Fire", 5200, "Tattoo", True, "Very Rare"),
  Item("Absorbing Tattoo, Force", 7200, "Tattoo", True, "Very Rare"),
  Item("Absorbing Tattoo, Lightning", 5200, "Tattoo", True, "Very Rare"),
  Item("Absorbing Tattoo, Necrotic", 6400, "Tattoo", True, "Very Rare"),
  Item("Absorbing Tattoo, Poison", 4400, "Tattoo", True, "Very Rare"),
  Item("Absorbing Tattoo, Psychic", 6400, "Tattoo", True, "Very Rare"),
  Item("Absorbing Tattoo, Radiant", 6400, "Tattoo", True, "Very Rare"),
  Item("Absorbing Tattoo, Thunder", 5200, "Tattoo", True, "Very Rare"),
  Item("+3 All Purpose Tool", 8200, "Class Item", True, "Very Rare"),
  Item("+3 Amulet of the Devout", 7200, "Class Item", True, "Very Rare"),
  Item("+3 Arcane Grimoire", 7200, "Class Item", True, "Very Rare"),
  Item("+3 Bloodwell Vial", 7200, "Class Item", True, "Very Rare"),
  Item("+3 Cloak of Protection", 10000, "Clothing", True, "Very Rare"),
  Item("+3 Dragonhide Belt", 5500, "Class Item", True, "Very Rare"),
  Item("+2 Fate Dealer's Deck", 4500, "Class Item", True, "Very Rare"),
  Item("+3 Moon Sickle", 7800, "Class Item", True, "Very Rare"),
  Item("+3 Rhythm Maker's Drum", 7200, "Class Item", True, "Very Rare"),
  Item("+3 Rod of the Pact Keeper", 8400, "Class Item", True, "Very Rare"),
  Item("+3 ___", 5300, "Armor", False, "Very Rare", SHIELDS),
  Item("+2 ___", 4800, "Armor", False, "Very Rare", ARMOR),
  Item("+3 Wand of the War Mage", 7600, "Wand/Staff", True, "Very Rare"),
  Item("+3 ___", 6900, "Weapon", False, "Very Rare", WEAPONS),
  Item("+3 Wraps of Unarmed Power", 7700, "Clothing", False, "Very Rare"),
  Item("Amethyst Lodestone", 6700, "Jewelry", True, "Very Rare"),
  Item("Amulet of the Planes", 8450, "Jewelry", True, "Very Rare"),
  Item("Animated ___", 5750, "Armor", True, "Very Rare", SHIELDS),
  Item("Antimagic ___", 6350, "Armor", True, "Very Rare", ARMOR),
  Item("Arcane Cannon", 11000, "Weapon", False, "Very Rare"),
  Item("Armor of Safeguarding", 7500, "Armor", True, "Very Rare", HEAVY_ARMOR),
  Item("Bag of Devouring", 6600, "Wondrous Item", False, "Very Rare"),
  Item("Baleful Talon", 7800, "Weapon", False, "Very Rare", DAGGER),
  Item("Barrier Tattoo (Very Rare)", 6000, "Tattoo", True, "Very Rare"),
  Item("Belt of Frost Giant Strength", 10000, "Clothing", True, "Very Rare"),
  Item("Belt of Stone Giant Strength", 10000, "Clothing", True, "Very Rare"),
  Item("Belt of Fire Giant Strength", 18000, "Clothing", True, "Very Rare"),
  Item("Bloodaxe", 7800, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Greataxe"]),
  Item("Bloodshed ___", 8800, "Weapon", True, "Very Rare", SWORDS),
  Item("___ of Melodies", 8000, "Weapon", True, "Very Rare", BOWS),
  Item("Candle of Invocation (Azoth)", 12000, "Wondrous Item", True, "Very Rare"),
  Item("Candle of Invocation (Zeshvax)", 12000, "Wondrous Item", True, "Very Rare"),
  Item("Candle of Invocation (Thalia Goldsmile)", 12000, "Wondrous Item", True, "Very Rare"),
  Item("Candle of Invocation (Eurydice)", 12000, "Wondrous Item", True, "Very Rare"),
  Item("Candle of Invocation (Æthelgrim)", 12000, "Wondrous Item", True, "Very Rare"),
  Item("Candle of Invocation (Al-Jazaar)", 12000, "Wondrous Item", True, "Very Rare"),
  Item("Candle of Invocation (Qualoth)", 12000, "Wondrous Item", True, "Very Rare"),
  Item("Candle of Invocation (Althwaina)", 12000, "Wondrous Item", True, "Very Rare"),
  Item("Candle of Invocation (Belthimer)", 12000, "Wondrous Item", True, "Very Rare"),
  Item("Candle of Invocation (Miggdzbarr)", 12000, "Wondrous Item", True, "Very Rare"),
  Item("Candle of Invocation (Kykvendi)", 12000, "Wondrous Item", True, "Very Rare"),
  Item("Carcosa Steel ___", 7500, "Armor", False, "Very Rare", [a for a in MEDIUM_ARMOR if a.name != "Hide"] + HEAVY_ARMOR),
  Item("Carpet of Flying (3 ft. x 5 ft.)", 6000, "Wondrous Item", False, "Very Rare"),
  Item("Carpet of Flying (4 ft. x 6 ft.)", 6600, "Wondrous Item", False, "Very Rare"),
  Item("Carpet of Flying (5 ft. x 7 ft.)", 7200, "Wondrous Item", False, "Very Rare"),
  Item("Carpet of Flying (6 ft. x 9 ft.)", 8000, "Wondrous Item", False, "Very Rare"),
  Item("Cauldron of Rebirth", 20000, "Wondrous Item", True, "Very Rare"),
  Item("Cloak of Arachnida", 5800, "Clothing", True, "Very Rare"),
  Item("Clockwork Armor", 5400, "Armor", True, "Very Rare", HEAVY_ARMOR),
  Item("Comet Spear", 8800, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Spear"]),
  Item("Crown of Whirling Comets", 7200, "Jewelry", True, "Very Rare"),
  Item("Crystal Ball", 12000, "Wondrous Item", True, "Very Rare"),
  Item("Crystalline Chronicle", 9650, "Class Item", True, "Very Rare"),
  Item("Dancing ___", 6800, "Weapon", True, "Very Rare", SWORDS),
  Item("Dawnsteel Greatsword", 18000, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Greatsword"]),
  Item("Deck of Dimensions", 6750, "Wondrous Item", True, "Very Rare"),
  Item("Deck of Wild Cards", 6250, "Wondrous Item", False, "Very Rare"),
  Item("Demon Armor", 5000, "Armor", True, "Very Rare", PLATE),
  Item("Dispelling Stone", 3400, "Consumable", False, "Very Rare"),
  Item("Dragon Scale Mail (Amethyst)", 9600, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Black)", 7000, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Blue)", 7000, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Brass)", 7000, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Bronze)", 7000, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Copper)", 7000, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Crystal)", 8300, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Deep)", 8300, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Emerald)", 8300, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Gold)", 7000, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Green)", 7000, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Moonstone)", 8300, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Red)", 7000, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Sapphire)", 7000, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Silver)", 7000, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (Topaz)", 8300, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Scale Mail (White)", 7000, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Scale Mail"]),
  Item("Dragon Vessel (Wakened)", 7400, "Wondrous Item", True, "Very Rare"),
  Item("Dragon's Wrath ___ (Wakened)", 9750, "Weapon", True, "Very Rare", WEAPONS),
  Item("Dragon-Touched Focus (Wakened)", 7150, "Wondrous Item", True, "Very Rare"),
  Item("Duskcrusher", 9400, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Warhammer"]),
  Item("Dwarven Plate", 5600, "Armor", False, "Very Rare", PLATE),
  Item("Dwarven Thrower", 12100, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Warhammer"]),
  Item("Efreeti Bottle", 15000, "Wondrous Item", False, "Very Rare"),
  Item("Elven Thrower", 12100, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Spear"]),
  Item("Energy Bow", 9700, "Weapon", True, "Very Rare", BOWS),
  Item("Executioner's Axe", 11000, "Weapon", False, "Very Rare", AXES + [w for w in WEAPONS if w.name == "Halberd"]),
  Item("Fate Cutter Shears", 7770, "Weapon", True, "Very Rare", DAGGER),
  Item("Figurine of Wondrous Power (Obsidian Steed)", 10000, "Wondrous Item", False, "Very Rare"),
  Item("Fools's ___", 7250, "Weapon", True, "Very Rare", SWORDS),
  Item("Forcebreaker ___", 7800, "Weapon", False, "Very Rare", BLUNT),
  Item("Frost Brand ___", 8350, "Weapon", True, "Very Rare", SWORDS + [w for w in WEAPONS if w.name == "Glaive"]),
  Item("Gauntlets of the Blizzard", 8800, "Clothing", True, "Very Rare"),
  Item("Ghost Step Tattoo", 6550, "Tattoo", True, "Very Rare"),
  Item("Hammer of Runic Focus", 5600, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Warhammer"]),
  Item("Hat of Many Spells", 5450, "Clothing", True, "Very Rare"),
  Item("Helm of Brilliance", 15400, "Clothing", True, "Very Rare"),
  Item("Bronze Horn of Valhalla", 5500, "Wondrous Item", False, "Very Rare"),
  Item("Horseshoes of a Zephyr", 4500, "Wondrous Item", False, "Very Rare"),
  Item("Hunter's Coat", 3600, "Armor", True, "Very Rare", [a for a in ARMOR if a.name == "Leather"]),
  Item("Anstruth Harp", 8250, "Class Item", True, "Very Rare"),
  Item("Ioun Stone of Absorption", 8600, "Jewelry", True, "Very Rare"),
  Item("Ioun Stone of Agility", 8000, "Jewelry", True, "Very Rare"),
  Item("Ioun Stone of Fortitude", 8000, "Jewelry", True, "Very Rare"),
  Item("Ioun Stone of Insight", 8000, "Jewelry", True, "Very Rare"),
  Item("Ioun Stone of Intellect", 8000, "Jewelry", True, "Very Rare"),
  Item("Ioun Stone of Leadership", 8000, "Jewelry", True, "Very Rare"),
  Item("Ioun Stone of Strength", 8000, "Jewelry", True, "Very Rare"),
  Item("Last Stand Armor", 7650, "Armor", False, "Very Rare", ARMOR),
  Item("Lifewell Tattoo", 12300, "Tattoo", True, "Very Rare"),
  Item("Lucent Destroyer", 20000, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Musket"]),
  Item("Lute of Thunderous Thumping", 6900, "Weapon", False, "Very Rare", [w for w in WEAPONS if w.name == "Club"]),
  Item("Manual of Bodily Health", 25000, "Wondrous Item", False, "Very Rare"),
  Item("Manual of Gainful Exercise", 25000, "Wondrous Item", False, "Very Rare"),
  Item("Manual of Clay Golems", 6600, "Wondrous Item", False, "Very Rare"),
  Item("Manual of Flesh Golems", 5000, "Wondrous Item", False, "Very Rare"),
  Item("Manual of Iron Golems", 10000, "Wondrous Item", False, "Very Rare"),
  Item("Manual of Stone Golems", 8300, "Wondrous Item", False, "Very Rare"),
  Item("Manual of Quickness of Action", 25000, "Wondrous Item", False, "Very Rare"),
  Item("Mirror of Life Trapping", 12100, "Wondrous Item", False, "Very Rare"),
  Item("Mistral Mantle", 7950, "Clothing", True, "Very Rare"),
  Item("Nimbus Coronet", 9750, "Jewelry", True, "Very Rare"),
  Item("Nine Lives Stealer ___", 9150, "Weapon", True, "Very Rare", SWORDS),
  Item("Nolzur's Marvelous Pigments", 8800, "Wondrous Item", False, "Very Rare"),
  Item("Oathbow", 20500, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Longbow"]),
  Item("Oil of Sharpness", 1000, "Consumable", False, "Very Rare"),
  Item("Orb of the Veil", 10000, "Wondrous Item", True, "Very Rare"),
  Item("Potion of Flying (long rest variant)", 500, "Consumable", False, "Very Rare"),
  Item("Potion of Cloud Giant Strength (long rest variant)", 6600, "Consumable", False, "Very Rare"),
  Item("Potion of Greater Invisibility", 1000, "Consumable", False, "Very Rare"),
  Item("Potion of Longevity", 5000, "Consumable", False, "Very Rare"),
  Item("Potion of Possibility (long rest variant)", 4500, "Consumable", False, "Very Rare"),
  Item("Potion of Speed", 2000, "Consumable", False, "Very Rare"),
  Item("Potion of Vitality", 1500, "Consumable", False, "Very Rare"),
  Item("Potion of Healing (Supreme)", 500, "Consumable", False, "Very Rare"),
  Item("Figurine of Wondrous Power (Carnelian Triceratops)", 6, "Wondrous Item", False, "Very Rare"),
  Item("Quarterstaff of the Acrobat", 6700, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Quarterstaff"]),
  Item("Reincarnation Dust", 5000, "Consumable", False, "Very Rare"),
  Item("Ring of Amity", 14000, "Jewelry", True, "Very Rare"),
  Item("Ring of Regeneration", 17550, "Jewelry", True, "Very Rare"),
  Item("Ring of Shooting Stars", 7850, "Jewelry", True, "Very Rare"),
  Item("Robe of Scintillating Colors", 8300, "Clothing", True, "Very Rare"),
  Item("Robe of Stars", 9650, "Clothing", True, "Very Rare"),
  Item("Rod of Absorption", 13400, "Wondrous Item", True, "Very Rare"),
  Item("Rod of Alertness", 7200, "Wondrous Item", True, "Very Rare"),
  Item("Rod of Hellish Flames", 10666, "Wondrous Item", True, "Very Rare"),
  Item("Rod of Security", 12080, "Wondrous Item", False, "Very Rare"),
  Item("Sage's Signet (Bear)", 5300, "Jewelry", True, "Very Rare"),
  Item("Sage's Signet (Hart)", 8450, "Jewelry", True, "Very Rare"),
  Item("Sage's Signet (Lion)", 8200, "Jewelry", True, "Very Rare"),
  Item("Sage's Signet (Wolf)", 6540, "Jewelry", True, "Very Rare"),
  Item("Sanctum Amulet", 8850, "Jewelry", True, "Very Rare"),
  Item("Sapphire Buckler", 10800, "Armor", True, "Very Rare", SHIELDS),
  Item("Scaled Ornament (Wakened)", 8950, "Jewelry", True, "Very Rare"),
  Item("Scimitar of Speed", 7210, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Scimitar"]),
  Item("Skull Helm", 13130, "Clothing", True, "Very Rare"),
  Item("Spellbane Iron ___", 7500, "Armor",  False, "Very Rare", [a for a in MEDIUM_ARMOR if a.name != "Hide"] + HEAVY_ARMOR),
  Item("Spell Scroll of ___ (6th level)", 6000, "Spell Scroll", False, "Very Rare", SIXTH),
  Item("Spell Scroll of ___ (7th level)", 12000, "Spell Scroll", False, "Very Rare", SEVENTH),
  Item("Spell Scroll of ___ (8th level)", 20000, "Spell Scroll", False, "Very Rare", EIGHTH),
  Item("Spellguard Shield", 7600, "Armor", True, "Very Rare", SHIELDS),
  Item("Staff of Dunamancy", 8400, "Wand/Staff", True, "Very Rare"),
  Item("Staff of Fire", 7420, "Wand/Staff", True, "Very Rare"),
  Item("Staff of Frost", 7420, "Wand/Staff", True, "Very Rare"),
  Item("Staff of Power", 18000, "Wand/Staff", True, "Very Rare"),
  Item("Staff of Striking", 8530, "Wand/Staff", True, "Very Rare"),
  Item("Staff of Thunder and Lightning", 8740, "Wand/Staff", True, "Very Rare"),
  Item("Starlight Protector", 6890, "Armor", True, "Very Rare", SHIELDS),
  Item("Stonemaker War Pick", 6400, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "War Pick"]),
  Item("___ of Sharpness", 4500, "Weapon", True, "Very Rare", [s for s in SWORDS if s.name != "Rapier" and s.name != "Shortsword"]),
  Item("Thunderbuss", 18000, "Weapon", False, "Very Rare", [w for w in WEAPONS if w.name == "Pistol"]),
  Item("Thunderous Greatclub", 13000, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Greatclub"]),
  Item("Tidecaller Trident", 7160, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Trident"]),
  Item("Tome of Clear Thought", 25000, "Wondrous Item", False, "Very Rare"),
  Item("Tome of Leadership and Influence", 25000, "Wondrous Item", False, "Very Rare"),
  Item("Tome of Understanding", 25000, "Wondrous Item", False, "Very Rare"),
  Item("Twilight Lantern", 7700, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Flail"]),
  Item("Wand of Curses", 13130, "Wand/Staff", False, "Very Rare"),  
  Item("Wand of Polymorph", 7000, "Wand/Staff", True, "Very Rare"),
  Item("___ of Throne's Command", 9999, "Weapon", True, "Very Rare", MARTIAL_WEAPONS),
  Item("Wyrmreaver Gauntlets", 8850, "Clothing", True, "Very Rare"),
  Item("Armor of Invulnerability", 25000, "Armor", True, "Legendary", PLATE),
  Item("+3 ___", 15000, "Armor", False, "Legendary", ARMOR),
  Item("+3 Fate Dealer's Deck", 9800, "Class Item", True, "Legendary"),
  Item("Belt of Cloud Giant Strength", 34000, "Clothing", True, "Legendary"),
  Item("Belt of Storm Giant Strength", 50000, "Clothing", True, "Legendary"),
  Item("Blackrazor", 66000, "Weapon", True, "Legendary", [w for w in WEAPONS if w.name == "Greatsword"]),
  Item("Blood Fury Tattoo", 15840, "Tattoo", True, "Legendary"),
  Item("Cloak of Invisibility", 10180, "Clothing", True, "Legendary"),
  Item("Crystal Ball of Mind Reading", 30000, "Wondrous Item", True, "Legendary"),
  Item("Crystal Ball of Telepathy", 30000, "Wondrous Item", True, "Legendary"),
  Item("Crystal Ball of True Seeing", 30000, "Wondrous Item", True, "Legendary"),
  Item("Cubic Gate", 38000, "Wondrous Item", False, "Legendary"),
  Item("Defender ___", 15000, "Weapon", True, "Legendary", SWORDS),
  Item("Dragon Vessel (Ascendant)", 55000, "Wondrous Item", True, "Legendary"),
  Item("Dragon's Wrath ___ (Ascendant)", 42000, "Weapon", True, "Legendary", WEAPONS),
  Item("Dragonlance (___)", 14000, "Weapon", True, "Legendary", [w for w in WEAPONS if w.name == "Lance" or w.name == "Pike"]),
  Item("Dragon-Touched Focus (Ascendant)", 22000, "Wondrous Item", True, "Legendary"),
  Item("Efreeti Chain", 20000, "Armor", True, "Legendary", [a for a in ARMOR if a.name == "Chain Mail"]),
  Item("Euryale's Aegis", 18000, "Armor", True, "Legendary", SHIELDS),
  Item("Fane Eater", 12000, "Weapon", True, "Legendary", [w for w in WEAPONS if w.name == "Battleaxe"]),
  Item("Flail of Tiamat", 35000, "Weapon", True, "Legendary", [w for w in WEAPONS if w.name == "Flail"]),
  Item("Flame Konda", 24420, "Weapon", True, "Very Rare", [w for w in WEAPONS if w.name == "Greataxe"]),
  Item("Gold Canary Figurine of Wondrous Power", 36000, "Wondrous Item", False, "Legendary"),
  Item("Hammer of Thunderbolts", 20000, "Weapon", True, "Legendary", [w for w in WEAPONS if w.name == "Maul"]),
  Item("Harp of Gilded Plenty", 24000, "Wondrous Item", True, "Legendary"),
  Item("Holy Avenger", 20000, "Weapon", True, "Legendary", SWORDS),
  Item("Horn of Valhalla (Iron)", 10000, "Wondrous Item", False, "Legendary"),
  Item("Ollamh Harp", 12000, "Class Item", True, "Legendary"),
  Item("Ioun Stone of Greater Absorption", 18000, "Jewelry", True, "Legendary"),
  Item("Ioun Stone of Mastery", 18600, "Jewelry", True, "Legendary"),
  Item("Ioun Stone of Regeneration", 20000, "Jewelry", True, "Legendary"),
  Item("Iron Flask", 30000, "Wondrous Item", False, "Legendary"),
  Item("Jester's Mask", 35000, "Clothing", True, "Legendary"),
  Item("Longbow of the Healing Hearth", 30000, "Weapon", True, "Legendary", [w for w in WEAPONS if w.name == "Longbow"]),
  Item("Luck Blade ___", 50000, "Weapon", True, "Legendary", SWORDS),
  Item("Matalok", 40000, "Weapon", True, "Legendary", [w for w in WEAPONS if w.name == "Warhammer"]),
  Item("Moonblade", 50000, "Weapon", True, "Legendary", SWORDS),
  Item("Obsidian Flint Dragon Plate", 14000, "Armor", False, "Legendary", PLATE),
  Item("Orb of Skoraeus", 33330, "Wondrous Item", True, "Legendary"),
  Item("Plate Armor of Etherealness", 7000, "Armor", True, "Legendary", PLATE),
  Item("Platinum Scarf", 27700, "Clothing", True, "Legendary"),
  Item("Potion of Amethyst Dragon's Mastery", 16000, "Consumable", False, "Legendary"),
  Item("Potion of Black Dragon's Mastery", 14000, "Consumable", False, "Legendary"),
  Item("Potion of Blue Dragon's Mastery", 16000, "Consumable", False, "Legendary"),
  Item("Potion of Brass Dragon's Mastery", 13000, "Consumable", False, "Legendary"),
  Item("Potion of Bronze Dragon's Mastery", 15000, "Consumable", False, "Legendary"),
  Item("Potion of Copper Dragon's Mastery", 14000, "Consumable", False, "Legendary"),
  Item("Potion of Crystal Dragon's Mastery", 12000, "Consumable", False, "Legendary"),
  Item("Potion of Deep Dragon's Mastery", 11000, "Consumable", False, "Legendary"),
  Item("Potion of Emerald Dragon's Mastery", 14000, "Consumable", False, "Legendary"),
  Item("Potion of Gold Dragon's Mastery", 17000, "Consumable", False, "Legendary"),
  Item("Potion of Green Dragon's Mastery", 15000, "Consumable", False, "Legendary"),
  Item("Potion of Moonstone Dragon's Mastery", 15000, "Consumable", False, "Legendary"),
  Item("Potion of Red Dragon's Mastery", 17000, "Consumable", False, "Legendary"),
  Item("Potion of Sapphire Dragon's Mastery", 15000, "Consumable", False, "Legendary"),
  Item("Potion of Topaz Dragon's Mastery", 13000, "Consumable", False, "Legendary"),
  Item("Potion of White Dragon's Mastery", 13000, "Consumable", False, "Legendary"),
  Item("Potion of Storm Giant Strength", 14500, "Consumable", False, "Legendary"),
  Item("Prehistoric Figurine of Wondrous Power (Jasper Tyrannosaurus Rex)", 39000, "Wondrous Item", True, "Legendary"),
  Item("Reaper's Scream", 27130, "Weapon", True, "Legendary", [w for w in WEAPONS if w.name == "Morningstar"]),
  Item("Ring of Air Elemental Command", 18000, "Jewelry", True, "Legendary"),
  Item("Ring of Earth Elemental Command", 18000, "Jewelry", True, "Legendary"),
  Item("Ring of Fire Elemental Command", 18000, "Jewelry", True, "Legendary"),
  Item("Ring of Water Elemental Command", 18000, "Jewelry", True, "Legendary"),
  Item("Ring of Djinni Summoning", 50000, "Jewelry", True, "Legendary"),
  Item("Ring of Invisibility", 25000, "Jewelry", True, "Legendary"),
  Item("Ring of Spell Turning", 16800, "Jewelry", True, "Legendary"),
  Item("Ring of Three Wishes", 100000, "Jewelry", False, "Legendary"),
  Item("Robe of the Archmagi", 20000, "Clothing", True, "Legendary"),
  Item("Rod of Lordly Might", 26000, "Wondrous Item", True, "Legendary"),
  Item("Rod of Resurrection", 42000, "Wondrous Item", True, "Legendary"),
  Item("Ruby Weave Gem", 35555, "Jewelry", True, "Legendary"),
  Item("Scaled Ornament (Ascendant)", 25000, "Jewelry", True, "Legendary"),
  Item("Scarab of Protection", 12120, "Jewelry", True, "Legendary"),
  Item("Shield of the Blazing Dreadnought", 22400, "Armor", True, "Legendary", SHIELDS),
  Item("Sovereign Glue", 22000, "Consumable", False, "Legendary"),
  Item("Spell Bottle", 20000, "Wondrous Item", True, "Legendary"),
  Item("Spell Scroll of ___ (9th level)", 50000, "Spell Scroll", False, "Legendary", NINTH),
  Item("Spindle of Fate", 23000, "Wondrous Item", True, "Legendary"),
  Item("Staff of the Magi", 50000, "Wand/Staff", True, "Legendary"),
  Item("Stonebreaker's Breastplate", 24500, "Armor", True, "Legendary", [a for a in ARMOR if a.name == "Breastplate"]),
  Item("Sword of Answering", 12700, "Weapon", True, "Legendary", [w for w in WEAPONS if w.name == "Longsword"]),
  Item("___ of the Planes", 38700, "Weapon", True, "Legendary", SWORDS),
  Item("Talisman of Pure Good", 77777, "Jewelry", True, "Legendary"),
  Item("Talisman of Ultimate Evil", 77777, "Jewelry", True, "Legendary"),
  Item("Topaz Annihilator", 65000, "Weapon", True, "Legendary", [w for w in WEAPONS if w.name == "Musket"]),
  Item("Universal Solvent", 22000, "Consumable", False, "Legendary"),
  Item("Vorpal ___", 25000, "Weapon", True, "Legendary", [w for w in SWORDS if w.name != "Shortsword" and w.name != "Rapier"]),
  Item("Wave", 75000, "Weapon", True, "Legendary", [w for w in WEAPONS if w.name == "Trident"]),
  Item("Well of Many Worlds", 30000, "Wondrous Item", False, "Legendary"),
  Item("Whelm", 59000, "Weapon", True, "Legendary", [w for w in WEAPONS if w.name == "Warhammer"]),
]

COMMON_ITEMS = [i for i in ITEMS if i.rarity == "Common"]
UNCOMMON_ITEMS = [i for i in ITEMS if i.rarity == "Uncommon"]
RARE_ITEMS = [i for i in ITEMS if i.rarity == "Rare"]
VERY_RARE_ITEMS = [i for i in ITEMS if i.rarity == "Very Rare"]
LEGENDARY_ITEMS = [i for i in ITEMS if i.rarity == "Legendary"]

ARMOR_ITEMS = [i for i in ITEMS if i.type == "Armor"]
CLASS_ITEMS = [i for i in ITEMS if i.type == "Class Item"]
CLOTHING_ITEMS = [i for i in ITEMS if i.type == "Clothing"]
CONSUMABLE_ITEMS = [i for i in ITEMS if i.type == "Consumable"]
JEWELRY_ITEMS = [i for i in ITEMS if i.type == "Jewelry"]
SPELL_SCROLL_ITEMS = [i for i in ITEMS if i.type == "Spell Scroll"]
TATTOO_ITEMS = [i for i in ITEMS if i.type == "Tattoo"]
WEAPON_ITEMS = [i for i in ITEMS if i.type == "Weapon"]
WAND_ITEMS = [i for i in ITEMS if i.type == "Wand/Staff"]
GENERAL_ITEMS = [i for i in ITEMS if i.type == "Wondrous Item"]

RARITIES = ["Legendary", "Very Rare", "Rare", "Uncommon", "Common"]
ITEM_TYPES = ["Wondrous Item", "Armor", "Class Item", "Clothing", "Consumable", "Jewelry", "Spell Scroll", "Tattoo", "Wand/Staff", "Weapon"]
